### ISSUE TITLE
Missing license text in batch and powershell scripts

### ISSUE THREAD

**Issue by danielli90** [Microsoft/Mobius#102]
License header should be added to all batch (.cmd) and powershell scripts (.ps1)

**Comment by mkinoti** [comment]
Test

**Comment by danielli90** [comment]
assigned to @mkinoti

**Comment by skaarthik** [comment]
@mkinoti - are you planning to work on this?

**Comment by skaarthik** [comment]
Removing the assignee due to inactivity

**Comment by Myasuka** [comment]
Already created a PR to fix this issue: https://github.com/Microsoft/Mobius/pull/557
