### ISSUE TITLE
Investigate SparkCLR compatibility in Linux

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#105]
Explore if Mono or .NET core can be used to run SparkCLR in Linux based Spark clusters

**Comment by rapoth** [comment]
@kai-zeng and I are looking into this.

**Comment by VenkateshSrini** [comment]
Hi Any updates on this. Is this library compatible with .NET core

**Comment by kai-zeng** [comment]
@VenkateshSrini Hi. Mobius is fully compatible with Mono 4.2+ starting from release 1.5.2. We are looking into the compatibility with .NET core now.

**Comment by VenkateshSrini** [comment]
Hi kai-zeng,
Thanks for your reply. We are typically looking for .NET core support as that is from Microsoft officially. Can you please tell us time line by which it will be available.

**Comment by jwkjng** [comment]
+1
