### ISSUE TITLE
get user confirmation before setting execution policy in RunSamples.cmd

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#123]
Set-ExecutionPolicy is used in RunSamples.cmd and it changes the user preference for the Windows PowerShell execution policy. A warning has to be displayed to the user and execution policy should be updated only upon confirmation from the user. If it is possible to check the execution policy prior to doing anything regarding that, it would be preferable.

**Comment by ohwang** [comment]
This can be done as easy as add ``-Confirm`` parameter to ``Set-ExecutionPolicy``

However, I find that the only PS script run in the this cmd file is ``downloadtools.ps1``, if this is the case it would be better to set ExecutionPolicy when invoke the script without altering the registry settings, i.e.
```
powershell -ExecutionPolicy Unrestricted -File downloadtools.ps1 run !VERBOSE!
```

**Comment by skaarthik** [comment]
Thanks @ohwang . I like the second option.

**Comment by skaarthik** [comment]
@ohwang suggestion added to the script.
