### ISSUE TITLE
Send out email notification after Travis CI build completes

### ISSUE THREAD

**Issue by tawan0109** [Microsoft/Mobius#164]
Currently no email notification is sent out after Travis CI build completes (at least no email for a passed build), it will be very helpful if Travis CI sends email notification to PR owner after each build, just like what Appveyor does.

**Comment by skaarthik** [comment]
+1 
Today Travis build failed but I was not notified. Seeing AppVeyor notification on successful build completion I assumed the same for Travis build but later noticed Travis failure in the PR checklist.

@kai-zeng & @danielli90 how easy is it to add the notification?

**Comment by skaarthik** [comment]
Closing the issue to due inactivity
