### ISSUE TITLE
Improve documentation comments on APIs

### ISSUE THREAD

**Issue by jayjaywg** [Microsoft/Mobius#212]
Some documentation comments on APIs were copied from Scala or Python. Some of them still contain Scala/Python specified comments tags (e.g, C{***} in scala). Need to revisit documentation on APIs.

**Comment by jthelin** [comment]
Also many items are missing API docs for public members, which gets flagged in the csharp build as CS1591 warnings.

For example:
```
Configuration\ConfigurationService.cs(214,9): warning CS1591: Missing XML comment for publicly visible type or member 'Microsoft.Spark.CSharp.Configuration.RunMode.UNKNOWN' 
```

You have to scroll down in the build log past a huge amount of mvn download "noise" to find these though :(

**Comment by skaarthik** [comment]
@hebinhuang improved code documentation in M2. Closing this for now. If more improvements are needed, we could open new issues to track specific work items.
