### ISSUE TITLE
improve unit test coverage in "Sql" namespace

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#274]
Some classes still have code coverage less than 75%. We need to increase the coverage to 75% or more.

See https://codecov.io/github/Microsoft/Mobius/csharp/Adapter/Microsoft.Spark.CSharp/Sql

**Comment by skaarthik** [comment]
@hebinhuang - looks like the following files still have lots of blocks missing CC. Are they hard to cover or not important?

- https://codecov.io/github/Microsoft/Mobius/csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrameNaFunctions.cs?ref=702d6d624f436da0a51a37315d455b38fbc234f8
- https://codecov.io/github/Microsoft/Mobius/csharp/Adapter/Microsoft.Spark.CSharp/Sql/Types.cs?ref=702d6d624f436da0a51a37315d455b38fbc234f8
- https://codecov.io/github/Microsoft/Mobius/csharp/Adapter/Microsoft.Spark.CSharp/Sql/Functions.cs?ref=702d6d624f436da0a51a37315d455b38fbc234f8

**Comment by skaarthik** [comment]
and this as well...https://codecov.io/github/Microsoft/Mobius/csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs?ref=702d6d624f436da0a51a37315d455b38fbc234f8

**Comment by hebinhuang** [comment]
There is a part 2 to cover these files - see https://github.com/Microsoft/Mobius/pull/395
Columns.cs,DataFrame.cs,Types.cs,DataFrameNaFunctions.cs,Functions.cs
