### ISSUE TITLE
RDD API review - new in 1.6.0

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#278]
Add new RDD APIs to SparkCLR
* http://spark.apache.org/docs/1.6.0/api/scala/index.html#org.apache.spark.rdd.RDD
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/rdd/PairRDDFunctions.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/rdd/DoubleRDDFunctions.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/rdd/SequenceFileRDDFunctions.html

**Comment by xiongrenyi** [comment]
1. The only new API I see by comparing with 1.5 is experimental combineByKeyWithClassTag API which has an extra implicit parameter ct:ClassTag[C] compared to existing combineByKey API. this doesn't seem to be applicable to C#?

2. Experimental tag removed from approximate count APIs

https://github.com/apache/spark/commit/6f81eae24f83df51a99d4bb2629dd7daadc01519

python still marked as experimental and it is said that there was some recent talk of deprecating the
 approximate sum, mean methods.

suggest not to make any changes in Mobius API for the above.

**Comment by skaarthik** [comment]
@xiongrenyi can this be closed?

**Comment by xiongrenyi** [comment]
yes
