### ISSUE TITLE
DStream API review - new in 1.6.0

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#280]
Add new DStream APIs to SparkCLR
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/DStream.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/PairDStreamFunctions.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/MapWithStateDStream.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/ConstantInputDStream.html

**Comment by tawan0109** [comment]
`MapWithStateDStream` has already been supported in Mobius.
https://github.com/Microsoft/Mobius/blob/master/csharp/Samples/Microsoft.Spark.CSharp/DStreamStateSample.cs#L49

**Comment by tawan0109** [comment]
`ConstantInputDStream` now is also supported by https://github.com/Microsoft/Mobius/commit/f6777a3098a2af31f57bdb970f80af57232ddac4

**Comment by tawan0109** [comment]
Except `MapWithStateDStream` and `ConstantInputDStream`, no other changes are found in 
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/DStream.html
* http://spark.apache.org/docs/1.6.0/api/scala/org/apache/spark/streaming/dstream/PairDStreamFunctions.html
