### ISSUE TITLE
StreamingContextIpcProxy.DirectKafkaStream doesn't work in Spark 1.6.0

### ISSUE THREAD

**Issue by qintao1976** [Microsoft/Mobius#284]
In StreamingContextIpcProxy.DirectKafkaStream, it calls the following method in Java side:

org.apache.spark.streaming.kafka.KafkaUtilsPythonHelper.createDirectStream

But this method doesn't exist in Spark 1.6.0

**Comment by skaarthik** [comment]
Fixed in https://github.com/Microsoft/Mobius/commit/db13e20118898f3c029655df0121370e16265ac0
