### ISSUE TITLE
SortByKey and TakeOrdered Incomplete Implementations

### ISSUE THREAD

**Issue by johnisag** [Microsoft/Mobius#338]
Hello,

I am testing SparkCLR and try to reimplement a python Spark project with it.
I notice that SortByKey is not implemented both in current release version and 1.6 Preview. 

Are there any plans for implementation? 

Moreover, from what I can see in the implementation of the TakeOrdered, there is no provision of passing a function for the sorting like in python and scala.
e.g. python: indexedData.takeOrdered(k, key = lambda x: -x[0])
       scala: rdd.takeOrdered(1)(Ordering[Int].reverse.on(x=>x.age))

So, the method signature could be something like:
public static T[] TakeOrdered<T>(this RDD<T> self, int num, Func<T,T> keySelector) 

I do not know if it is a good idea to change Spark method signatures to SparkClr specific ones. 

Thank you

**Comment by skaarthik** [comment]
Hi @johnisag - I guess the team just forgot to implement SortByKey method in https://github.com/Microsoft/SparkCLR/blob/master/csharp/Adapter/Microsoft.Spark.CSharp/Core/OrderedRDDFunctions.cs#L44. If you are interested in contributing, please feel free to implement it and send a PR.

RE: TakeOrdered implementation, I like your suggestion of exposing keySelector. Feel free to add an overload for TakeOrdered method with keySelector as a parameter and send a PR.

I hope someone you or someone else will contribute these changes before our next release (and also back port the changes to 1.5 branch).

Thanks.

**Comment by xiongrenyi** [comment]
I plan to put SortByKey at the bottom of my list targeting April, but anyone are welcome to take over at anytime

Thanks

**Comment by jayjaywg** [comment]
Merged with PR #353

**Comment by jayjaywg** [comment]
TakeOrdered with additional parameter keyFunc is merged #382
