### ISSUE TITLE
SaveAsTable for Hive

### ISSUE THREAD

**Issue by cschrammel** [Microsoft/Mobius#350]
The documentation mentions that SaveAsTable "only works with DataFrames that are created from a HiveContext".  Is there any way to create a HiveContext using Mobius?

**Comment by jayjaywg** [comment]
Hi @cschrammel - The team didn't implement HiveContext so currently it's not supported. We'll implement it before our next release and also back port it to branch 1.5.

**Comment by jayjaywg** [comment]
Merged to master branch with #380

**Comment by cschrammel** [comment]
Thank you!!!
