### ISSUE TITLE
fsharp "word count" example broke the build in Linux

### ISSUE THREAD

**Issue by HankG** [Microsoft/Mobius#441]
I am building a fresh Linux Mint VM for trying to get standalone cluster Spark/Mobius working.  After a checkout, pulling down Maven,Nuget and xsltproc from the standard repository and Mono and Java8 from their respective vendor repositories I get a build error when I run build/build.sh.  Rolling back one revision fixed it.  The error is in the WordCount demo which is consistent with that check in.

**Comment by skaarthik** [comment]
Can you share details on the build error? CI builds in Travis on Ubuntu work just fine.

**Comment by HankG** [comment]
Below is the output from the end of the build step when it tries to build Examples.sln:

```
===== Building /home/hankgrabowski/Development/Mobius/examples/Examples.sln =====
Restore NuGet packages ===================
Installing 'log4net 2.0.5'.
Installing 'Microsoft.SparkCLR 1.6.100'.
Successfully installed 'Microsoft.SparkCLR 1.6.100'.
Installing 'Newtonsoft.Json 7.0.1'.
Successfully installed 'Newtonsoft.Json 7.0.1'.
Installing 'Razorvine.Pyrolite 4.10.0.0'.
Successfully installed 'Razorvine.Pyrolite 4.10.0.0'.
Installing 'Razorvine.Serpent 1.12.0.0'.
Successfully installed 'Razorvine.Serpent 1.12.0.0'.
Successfully installed 'log4net 2.0.5'.
Installing 'FSharp.Core 4.0.0.1'.
Successfully installed 'FSharp.Core 4.0.0.1'.
Build Debug ==============================
XBuild Engine Version 12.0
Mono, Version 4.2.3.0
Copyright (C) 2005-2013 Various Mono authors
/home/hankgrabowski/Development/Mobius/examples/Examples.sln:  warning : /home/hankgrabowski/Development/Mobius/examples/Batch/WordCountFSharp/WordCountFSharp.fsproj: The required attribute "Project" in Import is empty
		Configuration: Debug Platform: AnyCPU
	Configuration: Debug Platform: AnyCPU
Configuration: Debug Platform: AnyCPU
Configuration: Debug Platform: AnyCPU
EventPublisher.cs(51,25): warning CS0219: The variable `message' is assigned but its value is never used
EventPublisher.cs(70,17): warning CS0219: The variable `timer' is assigned but its value is never used
Configuration: Debug Platform: AnyCPU
Configuration: Debug Platform: AnyCPU
/home/hankgrabowski/Development/Mobius/examples/Batch/WordCountFSharp/WordCountFSharp.fsproj: error : /home/hankgrabowski/Development/Mobius/examples/Batch/WordCountFSharp/WordCountFSharp.fsproj: The required attribute "Project" in Import is empty
Configuration: Debug Platform: AnyCPU
MessagePublisher.cs(40,17): warning CS0219: The variable `topicName' is assigned but its value is never used
MessagePublisher.cs(47,25): warning CS0219: The variable `message' is assigned but its value is never used
MessagePublisher.cs(63,17): warning CS0219: The variable `timer' is assigned but its value is never used
Configuration: Debug Platform: AnyCPU
===== Build FAILED for /home/hankgrabowski/Development/Mobius/examples/Examples.sln -- Debug with error 1 - CANNOT CONTINUE =====
Build Mobius .NET Examples failed, stop building.

```

**Comment by skaarthik** [comment]
Option no.1 in http://fsharp.org/use/linux indicates fsharp need to be explicitly installed along with Mono. Maybe you could try that. I do not know why Linux distribution used in Travis did not need any package in addition to Mono. It is possible that it is available by default in the Travis machines.

If installing fsharp package does not help, the next step is to try removing &lt;choose&gt; & &lt;otherwise&gt; elements in [fsproj](https://github.com/Microsoft/Mobius/blob/master/examples/Batch/WordCountFSharp/WordCountFSharp.fsproj#L41) file based on http://forums.xamarin.com/discussion/15382/f-project-fails-to-build-with-the-required-attribute-project-in-import-is-empty.

**Comment by HankG** [comment]
Will give it a shot and let you know...

**Comment by HankG** [comment]
Yes that worked.  I didn't realize F# wasn't installed when you did mono-complete.

**Comment by skaarthik** [comment]
Thanks for trying it out @HankG If you are interested, please feel free to send a PR with updates to the Linux instructions at https://github.com/Microsoft/Mobius/blob/master/notes/linux-instructions.md#prerequisites

**Comment by HankG** [comment]
Done. Thanks for the help!
