### ISSUE TITLE
Return CSharpBackend code 126 on OSX

### ISSUE THREAD

**Issue by slyons** [Microsoft/Mobius#452]
When I try to run the samples on OSX I get the following error:

```
[run-samples.sh] SPARK_VERSION=1.6.1, HADOOP_VERSION=2.6
[run-samples.sh] JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
[run-samples.sh] SPARK_HOME=/opt/dev/work/Mobius/build/localmode/../tools/spark-1.6.1-bin-hadoop2.6
[run-samples.sh] SPARKCLR_HOME=/opt/dev/work/Mobius/build/localmode/../runtime
[run-samples.sh] SPARKCSV_JARS=
[run-samples.sh] sparkclr-submit.sh --exe SparkCLRSamples.exe /opt/dev/work/Mobius/build/localmode/../runtime/samples spark.local.dir /opt/dev/work/Mobius/build/localmode/../runtime/Temp sparkclr.sampledata.loc /opt/dev/work/Mobius/build/localmode/../runtime/data debug
[sparkclr-submit.sh] Command to run  --name SparkCLRSamples --class org.apache.spark.deploy.csharp.CSharpRunner /opt/dev/work/Mobius/build/runtime/lib/spark-clr_2.10-1.6.101-SNAPSHOT.jar /opt/dev/work/Mobius/build/localmode/../runtime/samples /opt/dev/work/Mobius/build/localmode/../runtime/samples/SparkCLRSamples.exe  spark.local.dir /opt/dev/work/Mobius/build/localmode/../runtime/Temp sparkclr.sampledata.loc /opt/dev/work/Mobius/build/localmode/../runtime/data debug
[CSharpRunner.main] Starting CSharpBackend!
[CSharpRunner.main] Port number used by CSharpBackend is 60061
[CSharpRunner.main] adding key=spark.jars and value=file:/opt/dev/work/Mobius/build/runtime/lib/spark-clr_2.10-1.6.101-SNAPSHOT.jar to environment
[CSharpRunner.main] adding key=spark.app.name and value=SparkCLRSamples to environment
[CSharpRunner.main] adding key=spark.submit.deployMode and value=client to environment
[CSharpRunner.main] adding key=spark.master and value=local[*] to environment
[CSharpRunner.main] closing CSharpBackend
Requesting to close all call back sockets.
[CSharpRunner.main] Return CSharpBackend code 126
Utils.exit() with status: 126, maxDelayMillis: 1000
```

The build works and all unit tests work, but I can't seem to run samples or any custom code on Mobius.

**Comment by skaarthik** [comment]
@slyons - from the log above I see that you are passing "debug" as the command line parameter to "run-samples.sh". "debug" parameter is supported only in sparkclr-submit.sh for [debug mode execution](https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#debug-mode). Try running just one sample first using "run-samples.sh --torun pi* --verbose"

**Comment by slyons** [comment]
I'll give that a try, but keep in mind this was done through the run
samples script.

**Comment by skaarthik** [comment]
Did you just run run-samples.sh without any arguments?

**Comment by slyons** [comment]
That's all I did.

**Comment by slyons** [comment]
Here's all I did to repro the problem:

```
@scly ➜  Mobius git:(master) ✗ build/localmode/run-samples.sh
[run-samples.sh] SPARK_VERSION=1.6.1, HADOOP_VERSION=2.6
[run-samples.sh] JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
[run-samples.sh] SPARK_HOME=/opt/dev/work/Mobius/build/localmode/../tools/spark-1.6.1-bin-hadoop2.6
[run-samples.sh] SPARKCLR_HOME=/opt/dev/work/Mobius/build/localmode/../runtime
[run-samples.sh] SPARKCSV_JARS=
[run-samples.sh] sparkclr-submit.sh --exe SparkCLRSamples.exe /opt/dev/work/Mobius/build/localmode/../runtime/samples spark.local.dir /opt/dev/work/Mobius/build/localmode/../runtime/Temp sparkclr.sampledata.loc /opt/dev/work/Mobius/build/localmode/../runtime/data
[sparkclr-submit.sh] Command to run  --name SparkCLRSamples --class org.apache.spark.deploy.csharp.CSharpRunner /opt/dev/work/Mobius/build/runtime/lib/spark-clr_2.10-1.6.101-SNAPSHOT.jar /opt/dev/work/Mobius/build/localmode/../runtime/samples /opt/dev/work/Mobius/build/localmode/../runtime/samples/SparkCLRSamples.exe  spark.local.dir /opt/dev/work/Mobius/build/localmode/../runtime/Temp sparkclr.sampledata.loc /opt/dev/work/Mobius/build/localmode/../runtime/data
[CSharpRunner.main] Starting CSharpBackend!
[CSharpRunner.main] Port number used by CSharpBackend is 58053
[CSharpRunner.main] adding key=spark.jars and value=file:/opt/dev/work/Mobius/build/runtime/lib/spark-clr_2.10-1.6.101-SNAPSHOT.jar to environment
[CSharpRunner.main] adding key=spark.app.name and value=SparkCLRSamples to environment
[CSharpRunner.main] adding key=spark.submit.deployMode and value=client to environment
[CSharpRunner.main] adding key=spark.master and value=local[*] to environment
[CSharpRunner.main] closing CSharpBackend
Requesting to close all call back sockets.
[CSharpRunner.main] Return CSharpBackend code 126
Utils.exit() with status: 126, maxDelayMillis: 1000
```

**Comment by josephwinston** [comment]
I thought that on OS X, you needed to use mono to execute the application <http://stackoverflow.com/a/3385772>

**Comment by skaarthik** [comment]
@josephwinston - yes, Mono is a [requirement to build & run Mobius](https://github.com/Microsoft/Mobius/blob/master/notes/linux-instructions.md#prerequisites). @slyons mentioned he built Mobius. So I assume Mono is installed in his machine. 

One of my coworkers could repro this issue. He believes it is due to a missing file in the build drop location of SparkCLRSamples.exe. I will confirm that copying that file fixes this issue and post an update here. There is also a possibility that "mono" may have to be explicitly specified in the command line argument as a prefix to the driver executable (SparkCLRSamples.exe) inside run-samples.sh when invoking sparkclr-submit.sh. Adding "mono" prefix seems like a requirement in CentOS but not in Ubuntu.

**Comment by josephwinston** [comment]
Poor wording on my part in reporting the issue.

I agree with the later part of your statement @skaarthik, you need ```mono``` to execute a "PE32 executable for MS Windows (console) Intel 80386 32-bit Mono/.Net assembly" on OS X (output of ```file SparkCLRSamples.exe```) as well on other Unix systems where ```binfmt``` is not in use.  

This Linux specific hack of using ```binfmt``` that is **not** recommended is described in http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only 

The normal approach to this on Unix is to have a shell script.  Something like this from http://www.mono-project.com/docs/getting-started/application-deployment/#layout-recommendation:

```bash
 #!/bin/sh

# assume mono is on your path
 exec mono ${SPARKCLR_HOME}/build/runtime/private/SparkCLRSamples.exe "$@"
```

If you name this script say ```SparkCLRSamples.exe``` and place the real version in something like ```${SPARKCLR_HOME}/build/runtime/private/SparkCLRSamples.exe``` you won't have to change either ```scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala``` or the tests in ```scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala```  If you don't an use another suffix, the logic in these two files will need to be changed.

Another OS X issue is that ```sed -i``` does not work the same on OS X as the ```gnu``` version.  The hack is to run ```sed -i '' ...```

**Comment by skaarthik** [comment]
@josephwinston - thanks for the info. Mobius project can leverage your expertise in this area. It would be great if you can contribute to the documentation updates and other OSX related changes.

**Comment by skaarthik** [comment]
@slyons - do we need to keep this issue open? The write-up from @josephwinston is good and covers running Mobius in OS X.

**Comment by slyons** [comment]
I haven't had a chance to test it, but the issue can probably be put to rest
