### ISSUE TITLE
Exit code 255 with Mobius in yarn mode

### ISSUE THREAD

**Issue by ErikApption** [Microsoft/Mobius#455]
We have been able to deploy and run Mobius on HDP 2.4. Everything works fine in local mode but when we try yarn mode we get the following error. The application log has no other details

```
 Application application_1463585113649_0006 failed 2 times due to AM Container for appattempt_1463585113649_0006_000002 exited with exitCode: 255
For more detailed output, check application tracking page:http://hdp-apption.office.apption.com:8088/cluster/app/application_1463585113649_0006Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e12_1463585113649_0006_02_000001
Exit code: 255
Stack trace: ExitCodeException exitCode=255:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:576)
at org.apache.hadoop.util.Shell.run(Shell.java:487)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:753)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:303)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 255 
```

**Comment by skaarthik** [comment]
@ErikApption are you trying to run Mobius samples/examples?

**Comment by skaarthik** [comment]
What is your HDP environment - Linux or Windows?

**Comment by ErikApption** [comment]
This is HDP+Linux (centos 7). We are running our own Mobius code that queries Phoenix and Hive. We will try the built-in examples and see if we can reproduce the issue.

**Comment by ErikApption** [comment]
I can confirm that we have the same error with the wordcount example

**Comment by skaarthik** [comment]
@ErikApption - I assume you are just following instructions at https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#linux-instructions to run wordcound example. If you are doing something different, can you share the command you are using to run the example?

@qualiu - you have used Mobius in CentOS. You observed the need add "mono" prefix when passing the executable argument to sparkclr-submit.sh. Can you share you experience running wordcount example?

**Comment by ErikApption** [comment]
I can confirm that we are following the instructions from the wordcount example. Also we have not been able to prefix with "mono"

We are using:
`sparkclr-submit.sh --exe Program.sh.exe /path/to/program.exe/parent/dir`

where Program.sh.exe is in the same directory as Program.exe and contains:

```sh
#!/bin/sh
/usr/bin/mono Program.exe "$@"
```

**Comment by qualiu** [comment]
@ErikApption  @skaarthik 
I just modify 1 script : adding 1 line into Mobius/build/runtime/scripts/sparkclr-submit.sh
export SPARK_ARGS=$(echo "$SPARK_ARGS" | sed 's/\(\S\+\.exe\s\+\)/mono \1/ig')

This can solve  lack of "mono" before exe on CentOS.  
And needless to modify each program ( to add an extra shell).

But probably this still not the best solution, and the best solution could be register exe with "modprobe binfmt" : http://www.mono-project.com/archived/guiderunning_mono_applications/

**Comment by skaarthik** [comment]
@ErikApption - are you able to run a scala Spark application in this setup? (just making sure that you are getting the error above only when Mobius is used)

Do you see any error message related to Mobius in YARN resource-manager logs?

A fix (https://github.com/Microsoft/Mobius/commit/e35a903155d154f8cbf025a5c4044ad8a49f0de4) to using Mobius in Linux was pushed to the repo last week. Would you mind trying that out to see if it helps in anyway?

**Comment by qualiu** [comment]
@ErikApption + @skaarthik  I found a solution for running C# exe on CentOS 7 yesterday:
Just run one command : **echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register**
**But Please first check the path exists** : ls /proc/sys/fs/binfmt_misc/register
Then you can run ./CSharpExe directly and needless to type prefix "mono ./CSharpExe" or create an extra shell.

**Comment by skaarthik** [comment]
@ErikApption - can you confirm if the suggestion from @qualiu helps?

**Comment by ErikApption** [comment]
Issue is resolved we had some hanging processes in yarn that were causing this error. Mobius + Yarn is now working out of the box.
