### ISSUE TITLE
Use Registered IO + IOCP in C# Worker/Driver

### ISSUE THREAD

**Issue by hebinhuang** [Microsoft/Mobius#456]
We noticed that the performance of JAVA socket's receive is faster than .NET socket's, even both them is to call Windows Socket API. Currently, We just simply/directly use Socket class to receive/send data in C# Worker/Driver. So it is better to change it to improve the performance of the traffic between JVM and CLR.

Microsoft Windows 8 and Windows Server 2012 introduce new Windows Socket programming APIs - the Registered I/O networking extensions (RIO). RIO is a new set of high-speed networking APIs that provides increased networking performance with lower latency and jitter by using pre-registered data buffers and completion queues.

**Comment by hebinhuang** [comment]
Here is very simple comparison of Java socket and C# socket.
![image](https://cloud.githubusercontent.com/assets/17152782/15377733/becfd0e8-1d12-11e6-8d1f-d38490e32d2f.png)

![image](https://cloud.githubusercontent.com/assets/17152782/15377745/d1f2ef2a-1d12-11e6-846f-200a1d504f0f.png)

**Comment by skaarthik** [comment]
@hebinhuang ensure that the cross-platform support is not impacted with this Windows-only perf improvement.

**Comment by skaarthik** [comment]
Thanks for this new feature, @hebinhuang Closing this issue as the pending items are tracked separately.
