### ISSUE TITLE
YARN cluster mode failure in Linux

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#467]
Client mode works fine in Linux but cluster mode fails with the message like the following:
CSharpRunner.main]Cannot run program "SparkClrPi.exe": error=2, No such file or directory

We may have to add "." to the exe before launching it as a process in CSharpRunner.

@kai-zeng & @tawan0109 - FYI

**Comment by kai-zeng** [comment]
Agreed.

**Comment by skaarthik** [comment]
Fixed with https://github.com/Microsoft/Mobius/commit/4004001732470d619633ee311fd7e9ca56f79b8a
