### ISSUE TITLE
MSB4126 while building

### ISSUE THREAD

**Issue by josephwinston** [Microsoft/Mobius#480]
While following <https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md>, I received the following error after running ```Build.cmd```:

```
D:\home\josephwinston\src\Remote\GIT\Mobius\csharp\SparkCLR.sln.metaproj : error MSB4126: The specified solution configuration "Debug|X64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\home\josephwinston\src\Remote\GIT\Mobius\csharp\SparkCLR.sln]
```

This can be fixed by setting ```platform``` to ```Any CPU```  Perhaps, this should be part of the ```Build.cmd``` command.

**Comment by skaarthik** [comment]
@josephwinston I do not get this error when I build the master branch. Are you seeing this error in OS X?

**Comment by josephwinston** [comment]
This is on Windows 7, building from CMD running ```C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64``` eg "VS2015 x64 Native Tools Command Prompt"

**Comment by skaarthik** [comment]
Just learned that vcvarsall.bat enables [VC++ compiler toolset](https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx) for building native code. I have been using the [command prompt that enables .NET toolset](https://msdn.microsoft.com/en-us/library/ms229859(v=vs.110).aspx) and the documentation was meant to recommend using that.

**Comment by skaarthik** [comment]
@josephwinston - did you try using .NET dev prompt to build Mobius? Is there any follow-up needed from the Mobius devs on this issue?

**Comment by josephwinston** [comment]
Please close even though I haven't had the chance to try it with the correct decision prompt.

**Comment by skaarthik** [comment]
Ok, thanks. Please reopen if needed.
