### ISSUE TITLE
Can we upgrade C# (.NET >= 4.5;  Mono >= 4.4) ?

### ISSUE THREAD

**Issue by qualiu** [Microsoft/Mobius#491]
## Motivation : want to use some new feature
At least features like "**nameof**" and "**String Interpolation**" are very useful. 
Take "**String Interpolation**" as an example:
The old fashion usage :
`String.Format("***{0} *** {1} *** {2} ***", v1, a2, p3);`
The above usage is quite clumsy comparing to new usage and **vulnerable to changes** :
`$"{v1} *** {a2} *** {p3}"`

### What to do for upgrade
Only update the scripts (*.bat/*.cmd) **on Windows only** : (other platforms not specified version)
`SET VisualStudioVersion=12.0`
Change it to :
`SET VisualStudioVersion=14.0`

## Current compiler 
**Windows : Visual Studio 2013 / 12.0** : Specified in compilation script (build.cmd), need upgrade.
**Mono : 4.4.1** : Not specified version in scripts AND higher enough needless to upgrade.

And I noticed that we **already have higher version compilers in fact** (but downgrade using):
[Daily build on Linux : Mono](https://travis-ci.org/Microsoft/Mobius/builds/142634758)
`Mono JIT compiler version 4.4.1 (Nightly 4.4.1.0/4747417 Wed Jun 22 11:14:49 UTC 2016)`
[Daily build on Windows: Visual Studio](https://ci.appveyor.com/project/SparkCLR/sparkclr/build/1.6.2-SNAPSHOT.992)
`VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\`

## Validation for upgrade : ALL Passed on 3 Platforms

**Test code snip** 
`var exe = Path.GetFileName(System.Reflection.Assembly.GetExecutingAssembly().CodeBase);`
**New fashion :**
```
Console.WriteLine($"Usage    : {exe}  input-arguments, type = {nameof(testArgsQuotes)}");
```
**Old fashion :**
```
Console.WriteLine("Usage    : {0}  input-arguments, type = {1}", exe, "testArgsQuotes");
```

### 1. Windows
Visual Studio 2015 / Microsoft Visual Studio 14.0 
No doubt passed.
### 2. CentOS 7
```
[alone@cent71 ~]$ mono --version
Mono JIT compiler version 4.4.0 (Stable 4.4.0.142/81f38a9 Thu Apr 28 09:14:25 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
[alone@cent71 ~]$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
[alone@cent71 ~]$ uname -a
Linux cent71 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
#### 3. Ubuntu 16.04 LTS
```
ling@ku16:~$ mono --version
Mono JIT compiler version 4.4.0 (tarball Tue Jun 14 13:41:51 UTC 2016)
ling@ku16:~$ uname -a
Linux ku16 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ling@ku16:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)
```

**Comment by qualiu** [comment]
### What to do for upgrading C# version (.NET >= 4.5; Mono >= 4.4) 
Only update the scripts (*.bat/*.cmd) **on Windows only** :
`SET VisualStudioVersion=12.0`
Change it to :
`SET VisualStudioVersion=14.0`

**Comment by danielli90** [comment]
For Windows, .Net 4.5 is required. Good enough for Windows?

https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md#building-mobius
•Developer Command Prompt for Visual Studio 2013 or above, which comes with .NET Framework 4.5 or above. Note: Visual Studio 2015 Community Edition is FREE.

**Comment by qualiu** [comment]
Improvements in .NET 4.5 : https://msdn.microsoft.com/en-us/library/ms171868(v=vs.110).aspx#core
At least on related to us : (item 3)
Better performance through background garbage collection.

**Comment by skaarthik** [comment]
Mobius C# code is already built for .NET 4.5. See https://github.com/Microsoft/Mobius/blob/master/csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj#L12

**Comment by qualiu** [comment]
@skaarthik I probably post wrong requirement for the upgrade. Let me describe what happens first :
#### On Windows (already fine on Linux : CentOS / Ubuntu)
If I use the following code :
`Console.WriteLine($"Usage    : {exe}  input-arguments, type = {nameof(testArgsQuotes)}");`

And call {Mobius}\csharp\Build.cmd  will get compilation error as following:
```
testArgsQuotes.cs(30,35): error CS1056: Unexpected character '$' [d:\msgit\lqmMobius\test\csharp\testArgsQuotes\testArgsQuotes.csproj]
ParseKeyValuePair.cs(16,60): error CS1519: Invalid token '=' in class, struct, or interface member declaration [d:\msgit\lqmMobius\test\csharp\commonTestUtils\CommonTestUtils.csproj]
```

But if I update the script {Mobius}\csharp\Build.cmd will work fine:
`SET VisualStudioVersion=12.0`
Change it to :
`SET VisualStudioVersion=14.0`

#### So, What to do is not upgrade the .NET but ToolVersion/VisualStudioVersion?
like : https://github.com/Microsoft/Mobius/blob/master/csharp/Build.cmd#L9
![image](https://cloud.githubusercontent.com/assets/18525294/16679470/6b3091c2-451a-11e6-9af9-2107f99a0455.png)

(And I did not change following file, compilation passed)
https://github.com/Microsoft/Mobius/blob/master/csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj#L2

**Comment by danielli90** [comment]
C# 6.0 comes with VS14 (Visual Studio 15) - https://msdn.microsoft.com/en-us/library/hh156499.aspx
•	String Interpolation
You can use string interpolation expressions to construct strings. An interpolated string expression looks like a template string that contains expressions. C# creates a string by replacing the expressions with the ToString represenations of the expressions’ results. An interpolated string is easier to understand with respect to arguments than Composite Formatting.

@qualiu - I think you are asking to upgrade compiler to VS 14 (Visual Studio 2015) for C# 6.0 feature of String Interpolation.

Mobius Project requires VS 12 (Visual Studio 2013) and above.

Two questions then - (1) what is the impact of requiring VS 14 (Visual Studio 2015) to compile Mobius Project?  (2) what is the impact of staying with VS 12 (Visual Studio 2013) and not benefiting from latest C# 6.0 features, such as String Interpolation?

**Comment by qualiu** [comment]
Thanks @danielli90 ! Probably it's a topic about the "build tool version" and "target framework version" as @skaarthik  said.
The phenomenon in brief : (and both of following compilation passed)
1) Nothing to change compile OK in VS2015 (compile within IDE) , Target framework = 4.5.
2) Change Build.cmd :` SET VisualStudioVersion=14.0 ` then call Build.cmd OK.
In addition : my local machine has only one version : Visual Studio 2015.

**Comment by danielli90** [comment]
@qualiu, just make sure we are on the same page regarding your ask here - 

"String interploation" and "nameof" are new C# 6.0 features; C# 6.0 is supported only in VS2015 (and above). When VS 2013 is used, "String interploation" and "nameof" trigger compiler error, as you observed.

If you remove "String interpolation" and "nameof" in your code, VS 2013 should be able to compile. For example change the following - 
`Console.WriteLine($"Usage : {exe} input-arguments, type = {nameof(testArgsQuotes)}");`
to: 
`Console.WriteLine("Usage : {0} input-arguments, type = testArgsQuotes", exe);`

**C# 6.0 introduces a good list of useful features - https://msdn.microsoft.com/en-us/library/hh156499.aspx. But let's understand the pros and cons first.** 

@jthelin, any comments? has Orleans embrace C# 6.0 yet?

**Comment by qualiu** [comment]
@danielli90 : yes, but from phenomenon seems we don't need to upgrade to C# 6.0, just need to upgrade the build tool to VS2015, and on Windows only. (Linux are already well)

**Comment by jthelin** [comment]
@danielli90 - Orleans has switched to using VS2015 for build/test, but is trying to still be able to run code on .NET 4.5.x for now.

This generally means avoiding the C# 6.0 changes that require updated NET 4.6 runtime, but there are  some C# 6.0 features like string interpolation that are done at compile time and remain compatible on old 4.5.x runtime. Given that most of those compile-time 6.0 extras are mostly syntactic-sugar, i find in my other projects it is easier to just avoid the borderline cases too.

Thankfully ReSharper has a way of turning off prompts for 6.0 features, which i do on my machines.
https://resharper-support.jetbrains.com/hc/en-us/community/posts/207462505-Disable-new-C-6-0-features-in-ReSharper-

The longer-term goal for Orleans is to support .NET Core 1.0 [cross-platform server runtime], but that will be a bigger step and not quite ready yet.

HTH.

**Comment by danielli90** [comment]
Thanks @jthelin. 

@qualiu, given Mobius needs to support .Net 4.5.x as well, we can avoid those C# 6.0 syntactic-sugar and configure ReSharper accordingly. Does that make sense to you?

**Comment by qualiu** [comment]
@danielli90 : OK, thanks!   And thanks @jthelin for your expert comment.
