### ISSUE TITLE
Error in calling "sparkclr-submit.cmd debug" command

### ISSUE THREAD

**Issue by madhus84** [Microsoft/Mobius#496]
I am trying to use mobius spark clr for my internal project. i have built spark clr and when i call "sparkclr-submit.cmd debug", its throwing me below error that it cant find a class

SPARKCLR_JAR=spark-clr_2.10-1.6.101-PREVIEW1.jar
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/Seq
        at org.apache.spark.deploy.csharp.CSharpRunner.main(CSharpRunner.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

Am i missing something here? I downloaded branch 1.6

**Comment by hebinhuang** [comment]
@madhus84, the error is caused by missing Spark bits. Please make sure you have downloaded spark bits. You can run "RunSamples.cmd" from "build/localmode" of source code to download Spark bits.

Please see "https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md#running-in-local-mode-dev-environment" for the detail of running "RunSamples.cmd".

Then set SPARK_HOME to Spark bits (you can find  toos\spark*  directory). see https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#pre-requisites

**Comment by madhus84** [comment]
hi

I ran the Runsamples.cmd and i got the below output...

Error is "Error: Could not find or load main class
org.apache.spark.launcher.SparkCLRSubmitArguments"

[RunSamples.cmd] CWD=
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode
VisualStudioVersion = "12.0"
[RunSamples.cmd] SPARK_VERSION=1.6.1, HADOOP_VERSION=2.6
[downloadtools] hadoopVersion=2.6, sparkVersion=1.6.1
[downloadtools.Download-File]
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\l
ocalmode\..\tools\TarTool.zip exists. No need to download.
[downloadtools.Unzip-File] Extracting
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6
\build\localmode\..\tools\TarTool.zip to
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch
1.6\build\localmode\..\tools ...
Exception calling "OpenRead" with "1" argument(s): "Central Directory
corrupt."
At
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\downloadtools.ps1:
130 char:50
+     $entries = [IO.Compression.ZipFile]::OpenRead <<<< ($zipFile).Entries
    + CategoryInfo          : NotSpecified: (:) [],
MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Exception calling "ExtractToFile" with "3" argument(s): "Value cannot be
null.
Parameter name: source"
At
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\downloadtools.ps1:
136 char:62
+             [IO.Compression.ZipFileExtensions]::ExtractToFile <<<< ($_,
$targetpath, $true)
    + CategoryInfo          : NotSpecified: (:) [],
MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

[downloadtools.Unzip-File] Extraction completed. Time taken: 153
milliseconds
[downloadtools.Download-File]
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\l
ocalmode\..\tools\spark-1.6.1-bin-hadoop2.6.tgz exists. No need to download.
[downloadtools.Untar-File] Extracting
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6
\build\localmode\..\tools\spark-1.6.1-bin-hadoop2.6.tgz to
C:\Users\mnatarajan\Downloads\Mobiusbran
ch1.6\Mobiusbranch1.6\build\localmode\..\tools ...
The term
'C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\Ta
rTool.exe' is not recognized as the name of a cmdlet, function, script
file, or operable program. C
heck the spelling of the name, or if a path was included, verify that the
path is correct and try a
gain.
At line:1 char:2
+ & <<<<
 "C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\T
arTool.exe"
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\
spark-1.6.1-bin-hadoop2.6.tgz
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\l
ocalmode\..\tools
    + CategoryInfo          : ObjectNotFound:
(C:\Users\mnatar...ols\TarTool.exe:String) [], Comma
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[downloadtools.Untar-File] Extraction completed. Time taken: 42 milliseconds
[downloadtools.Download-RuntimeDependencies]
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbr
anch1.6\build\localmode\..\tools\winutils\bin\winutils.exe exists already.
No download and extracti
on needed
[downloadtools.Replace-VariableInFile] variable=\${env:TEMP},
value=c:/users/mnatar~1/appdata/local
/temp,
sourceFile=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\spa
rk.conf\log4j.properties,
targetFile=c:\users\mnatar~1\appdata\local\temp\log4j.properties.temp
[Replace-VariableInFile] [07/11/2016 19:03:34] replace \${env:TEMP} in
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\spark.conf\log4j.properties
to produce c:\users\mnatar~1\appdata\local\temp\log4j.properties.temp
Copy-Item : Could not find a part of the path
'C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobius
branch1.6\build\tools\spark-1.6.1-bin-hadoop2.6\conf'.
At
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\downloadtools.ps1:
415 char:18
+         copy-item <<<<   $scriptDir\spark.conf\*.properties $S_HOME\conf
-force
    + CategoryInfo          : NotSpecified: (:) [Copy-Item],
DirectoryNotFoundException
    + FullyQualifiedErrorId :
System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.C
   opyItemCommand

Copy-Item : Could not find a part of the path
'C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobius
branch1.6\build\tools\spark-1.6.1-bin-hadoop2.6\conf\log4j.properties'.
At
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\downloadtools.ps1:
416 char:18
+         copy-item <<<<   $targetFile $S_HOME\conf\log4j.properties -force
    + CategoryInfo          : NotSpecified: (:) [Copy-Item],
DirectoryNotFoundException
    + FullyQualifiedErrorId :
System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.C
   opyItemCommand

[downloadtools.Replace-VariableInFile]
variable=<appender-ref\s*ref="ConsoleAppender"\s*/>, value=<
!--<appender-ref ref="ConsoleAppender" />-->,
sourceFile=CSharpWorker.exe.config.orginal, targetFil
e=CSharpWorker.exe.config
[Replace-VariableInFile] [07/11/2016 19:03:34] replace
<appender-ref\s*ref="ConsoleAppender"\s*/> in
CSharpWorker.exe.config.orginal to produce CSharpWorker.exe.config
[downloadtools.Update-VerboseMode] enabled console appender in
CSharpWorker.exe.config, under C:\Us
ers\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\samples
[downloadtools.Replace-VariableInFile]
variable=<appender-ref\s*ref="ConsoleAppender"\s*/>, value=<
!--<appender-ref ref="ConsoleAppender" />-->,
sourceFile=SparkCLRSamples.exe.config.orginal, target
File=SparkCLRSamples.exe.config
[Replace-VariableInFile] [07/11/2016 19:03:34] replace
<appender-ref\s*ref="ConsoleAppender"\s*/> in
SparkCLRSamples.exe.config.orginal to produce SparkCLRSamples.exe.config
[downloadtools.Update-VerboseMode] enabled console appender in
SparkCLRSamples.exe.config, under C:
\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\samples
[RunSamples.cmd] UpdateRuntime.cmd
set
path=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools;%path%
set
SPARK_HOME=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\spark-1.6.1-bin-hadoop2.6
set
path=%path%;C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\spark-1.6.1-bin-hadoop2.6\bin
set
HADOOP_HOME=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\winutils
[RunSamples.cmd] SPARKCLR_JAR=
[RunSamples.cmd] JAVA_HOME=C:\Program Files\Java\jdk1.8.0_65
[RunSamples.cmd]
SPARK_HOME=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\tools\spark-1.6.1-bin-hadoop2.6
[RunSamples.cmd]
SPARKCLR_HOME=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime
[RunSamples.cmd]
SPARKCLR_EXT_JARS=C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\dependencies\spark-csv_2.10-1.3.0.jar,C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\dependencies\commons-csv-1.1.jar
[RunSamples.cmd] CWD=
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\scripts
 Volume in drive C is Windows
 Volume Serial Number is D591-ABA7

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime

07/11/2016  06:41 PM    <DIR>          .
07/11/2016  06:41 PM    <DIR>          ..
07/11/2016  06:06 PM    <DIR>          bin
07/11/2016  06:03 PM    <DIR>          data
07/11/2016  06:03 PM    <DIR>          dependencies
07/11/2016  06:58 PM    <DIR>          lib
07/11/2016  06:41 PM    <DIR>          samples
07/11/2016  06:04 PM    <DIR>          scripts
07/11/2016  06:41 PM    <DIR>          Temp
               0 File(s)              0 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\bin

07/11/2016  06:06 PM    <DIR>          .
07/11/2016  06:06 PM    <DIR>          ..
07/11/2016  06:03 PM            26,112 CSharpWorker.exe
06/03/2016  05:32 PM             1,737 CSharpWorker.exe.config
07/11/2016  06:03 PM            38,400 CSharpWorker.pdb
07/11/2016  05:26 PM             1,968 load-spark-env.cmd
12/10/2015  05:55 PM           304,640 log4net.dll
12/10/2015  05:55 PM         1,533,153 log4net.xml
07/11/2016  06:03 PM           260,608 Microsoft.Spark.CSharp.Adapter.dll
07/11/2016  06:03 PM           642,560 Microsoft.Spark.CSharp.Adapter.pdb
06/22/2015  11:06 AM           520,192 Newtonsoft.Json.dll
06/22/2015  11:06 AM           501,178 Newtonsoft.Json.xml
07/11/2016  06:03 PM            74,240 Razorvine.Pyrolite.dll
08/08/2015  08:29 PM            40,960 Razorvine.Serpent.dll
              12 File(s)      3,945,748 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\data

07/11/2016  06:03 PM    <DIR>          .
07/11/2016  06:03 PM    <DIR>          ..
06/03/2016  05:32 PM               772 csvtestlog.txt
06/03/2016  05:32 PM             1,733 market.tab
06/03/2016  05:32 PM               415 metricslog.txt
06/03/2016  05:32 PM               173 order.json
06/03/2016  05:32 PM               330 people.json
06/03/2016  05:32 PM               625 requestslog.txt
06/03/2016  05:32 PM               980 words.txt
               7 File(s)          5,028 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\dependencies

07/11/2016  06:03 PM    <DIR>          .
07/11/2016  06:03 PM    <DIR>          ..
07/11/2016  06:03 PM            36,888 commons-csv-1.1.jar
07/11/2016  06:03 PM               730 ReadMe.txt
07/11/2016  06:03 PM           139,677 spark-csv_2.10-1.3.0.jar
07/11/2016  06:03 PM        13,350,140
spark-streaming-kafka-assembly_2.10-1.6.1.jar
               4 File(s)     13,527,435 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\lib

07/11/2016  06:58 PM    <DIR>          .
07/11/2016  06:58 PM    <DIR>          ..
07/11/2016  06:03 PM           298,114 spark-clr_2.10-1.6.101-PREVIEW1.jar
               1 File(s)        298,114 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\samples

07/11/2016  06:41 PM    <DIR>          .
07/11/2016  06:41 PM    <DIR>          ..
07/11/2016  06:03 PM            26,112 CSharpWorker.exe
07/11/2016  07:03 PM             1,781 CSharpWorker.exe.config
06/03/2016  05:32 PM             1,737 CSharpWorker.exe.config.orginal
07/11/2016  06:03 PM            38,400 CSharpWorker.pdb
12/10/2015  05:55 PM           304,640 log4net.dll
12/10/2015  05:55 PM         1,533,153 log4net.xml
07/11/2016  06:03 PM           260,608 Microsoft.Spark.CSharp.Adapter.dll
07/11/2016  06:03 PM           642,560 Microsoft.Spark.CSharp.Adapter.pdb
07/11/2016  06:03 PM             7,168 Microsoft.Spark.CSharp.Utils.dll
07/11/2016  06:03 PM            17,920 Microsoft.Spark.CSharp.Utils.pdb
06/22/2015  11:06 AM           520,192 Newtonsoft.Json.dll
06/22/2015  11:06 AM           501,178 Newtonsoft.Json.xml
12/01/2015  10:51 PM           273,920 nunit.framework.dll
12/01/2015  10:51 PM           855,401 nunit.framework.xml
07/11/2016  06:03 PM            74,240 Razorvine.Pyrolite.dll
08/08/2015  08:29 PM            40,960 Razorvine.Serpent.dll
06/03/2016  05:32 PM             2,407 samplesusage.md
07/11/2016  06:03 PM           136,704 SparkCLRSamples.exe
07/11/2016  07:03 PM             3,263 SparkCLRSamples.exe.config
06/03/2016  05:32 PM             3,199 SparkCLRSamples.exe.config.orginal
07/11/2016  06:03 PM           228,864 SparkCLRSamples.pdb
              21 File(s)      5,474,407 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\scripts

07/11/2016  06:04 PM    <DIR>          .
07/11/2016  06:04 PM    <DIR>          ..
06/03/2016  05:32 PM             3,610 sparkclr-submit.cmd
06/03/2016  05:32 PM             3,044 sparkclr-submit.sh
               2 File(s)          6,654 bytes

 Directory of
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\runtime\Temp

07/11/2016  06:41 PM    <DIR>          .
07/11/2016  06:41 PM    <DIR>          ..
               0 File(s)              0 bytes

     Total Files Listed:
              47 File(s)     23,257,386 bytes
              23 Dir(s)  62,001,946,624 bytes free
[RunSamples.cmd] call sparkclr-submit.cmd --jars
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\dependencies\spark-csv_2.10-1.3.0.jar,C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\dependencies\commons-csv-1.1.jar
-exe SparkCLRSamples.exe
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\samples
spark.local.dir
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\Temp
sparkclr.sampledata.loc
C:\Users\mnatarajan\Downloads\Mobiusbranch1.6\Mobiusbranch1.6\build\localmode\..\runtime\data
SPARKCLR_JAR=spark-clr_2.10-1.6.101-PREVIEW1.jar
===== sparkclr-submit FAILED error 1 =====

Error: Could not find or load main class
org.apache.spark.launcher.SparkCLRSubmitArguments

Is it known?

thanks,
Madhu

**Comment by madhus84** [comment]
hi

Please ignore the previous mail.. there was an error in extracting
spark-1.6.1-bin-hadoop2.6.tgz
for some reason.. manually extracted to appropriate folder and retried. now
its completed... thanks for your help

Thanks,
Madhu

**Comment by hebinhuang** [comment]
@madhus84, you missed the Env variable "HADOOP_HOME". 
if you used  RunSamples.cmd  to run Mobius samples, you can find  toos\winutils  directory (under  build  directory) that can be used as HADOOP_HOME
(https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#pre-requisites)

**Comment by madhus84** [comment]
Hi

Is there any custom receiver i can use? I want to use spark clr from
webservice layer. For certain rest apis i want to generate dstream and pass
it to spark streaming apis.. Is there anyway i can do this?

PS: i am unable to post on github since i forgot my password and the forgot
password link isnt working.

Thanks,
Madhu
