### ISSUE TITLE
Adding a custom receiver for Spark Streaming

### ISSUE THREAD

**Issue by ppatierno** [Microsoft/Mobius#514]
If we have a custom receiver library, what's the right way to integrate in Mobius. I see something similar with Event Hub connector for example. Should be the StreamingContextIpcProxy modified in order to expose a new custom receiver ?

Thanks,
Paolo.

**Comment by skaarthik** [comment]
You do not have to do what was done for adding Event Hubs API to Mobius. That approach is appropriate for supporting a source (like Event Hubs) natively in Mobius. However, if your code is in C# and want to use that to create DStream, you could follow `DStreamCSharpInputSample` sample at https://github.com/Microsoft/Mobius/blob/master/csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs#L298

cc: @qintao1976

**Comment by ppatierno** [comment]
@skaarthik my connector is developed in Scala with a reliable receiver implementation. I'd like to provide it like Kafka and Event Hub ones natively in Mobius. I think it's the only way because it isn't written in C#

**Comment by skaarthik** [comment]
@ppatierno in that case, you could follow the same approach as Event Hubs support in Mobius and use your custom connector with Mobius.

**Comment by ppatierno** [comment]
@skaarthik ok so in that case I'll open a PR for the project ;)
