### ISSUE TITLE
Custom receiver for spark streaming

### ISSUE THREAD

**Issue by madhus84** [Microsoft/Mobius#518]
Hi 

Can i define my own custom receiver ? I am using version 1.6. I want to use spark clr from webservice layer. For certain rest apis i want to generate dstream to be consumed by spark streaming apis.. Is there anyway i can do this? 

Thanks,
Madhu

**Comment by madhus84** [comment]
hi 

Any help here would be greatly appreciated? 

Thanks,
Madhu

**Comment by qintao1976** [comment]
Hi

We provide an simple API to control data injection to Mobius streaming application.

        /// <summary>
        /// Create an input stream that user can control the data injection by C# code
        /// </summary>
        /// <param name="ssc">Spark Streaming Context</param>
        /// <param name="numPartitions">number of partitions</param>
        /// <param name="func">
        /// function provided by user to inject data to the DStream.
        /// it has two input parameters: time and partitionIndex
        /// it should return IEnumerable of injected data
        /// </param>
        /// <returns>A DStream object</returns>
        public static DStream<T> CreateStream<T>(StreamingContext ssc, int numPartitions, Func<double, int, IEnumerable<T>> func)
        {
            Func<double, RDD<T>> generateRDDFunc = new CSharpInputDStreamGenerateRDDHelper<T>(numPartitions, func).Execute;
            return CreateStream<T>(ssc, generateRDDFunc);
        }

An sample can be found in https://github.com/Microsoft/Mobius/blob/master/csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs

internal static void DStreamCSharpInputSample() 

Can you take a look and see if it meets your requirement?

Thanks

Tao Qin

**Comment by madhus84** [comment]
Hi Tao

Thanks for your help .. let me try this. this is not yet in any release rite. 

Thanks,
Madhu

**Comment by skaarthik** [comment]
@madhus84 - that's correct. It will be in the next release (planned for next week). In the meantime, build Mobius from master branch.

**Comment by skaarthik** [comment]
@madhus84 - anything further needed on this issue? can this be closed?

**Comment by madhus84** [comment]
Hi Kaarthik

This can be closed.

Thanks,
Madhu

**Comment by madhus84** [comment]
Hi

Can we use spark CLR to monitor data from webserver? Below are my
observations so far.

From what i saw, sparkclr-submit.cmd in debug mode allows for CSharpBackend
process to start. The port number is printed to console which i can use
from console app for testing.
Else if i specify sparkclr-submit.cmd in localmode , it expects parameter
--exe to be specified. In this case, i dont want to pass --exe since its
w3wp. In localmode, the port no is written to some environment variable
CSHARPBACKEND_PORT

So i dont seem to have way to get port no as well as not specify --exe
parameter. Is there any way around? Or am i missing something?

Thanks,
Madhu
