### ISSUE TITLE
Expose hadoopConfiguration in SparkContext

### ISSUE THREAD

**Issue by delulu** [Microsoft/Mobius#527]
Hi,

I need to write data to remote hdfs in my spark applications.

by default, dfs client will use ip address to connect to datanode, while the ip address is private and can't be reachable in spark cluster.

so, I want to add some custom hdfs setting to support multi-homed networks.

but the SparkContext class in Mobius did not provide a way to modify hadoopConfiguration in runtime, while it's supported in Scala API.

so could you guys enable it in Mobius?

Thanks,
Delu

**Comment by qualiu** [comment]
You've caught a good issue! :+1:

**Comment by skaarthik** [comment]
@delulu - is exposing hadoop configuration the only way to achieve what you are trying to do? Is there any other way to pass hadoop configuration to Spark job through command line parameter or config files?

**Comment by skaarthik** [comment]
@delulu - can you share the methods in [HadoopConfiguration](http://hadoop.apache.org/docs/current/api/org/apache/hadoop/conf/Configuration.html) you might be interested in.

**Comment by delulu** [comment]
@skaarthik - I would like to use the set method below to add some properties.

// Set the value of the name property.
void set(String name, String value)

**Comment by delulu** [comment]
@skaarthik - hadoop configuration can't be passed to Spark job through cmd line parameter, and I've tried to update hdfs-site.xml in HADOOP_CONF_DIR on my client box before submitting spark job, but it didn't work as expected. 

so it would be nice if we can update hadoop configuration in runtime, since it's supported in scala api.

**Comment by skaarthik** [comment]
@delulu try using the feature in build https://github.com/Microsoft/Mobius/releases/tag/v1.6.200-PREVIEW-1.

**Comment by delulu** [comment]
@skaarthik thank you for such a quick response! I've applied your changes and it works well. 
Also, I want to correct my previous comment - actually we can pass hadoop configuration **with a prefix "spark.hadoop."** to spark job through cmd line params.
