### ISSUE TITLE
Should we use relative path instead of absolute path in notes?

### ISSUE THREAD

**Issue by Myasuka** [Microsoft/Mobius#550]
Spark official docs use relative path instead of absolute path, such as [submitting-applications](http://spark.apache.org/docs/latest/submitting-applications.html). I think it's better to use relative path in documentation since not every user have the specific path and will not make users feel confused.
Currently, documentations in Mobius mainly use absolute paths, such as [windows-instructions](https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md) and [running-mobius-app](https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md). What's more, the absolute paths have different folder names, such as `c:\dependency\` and `C:\MobiusDependencies\`, which would also make users easily feel confused.

**Comment by qualiu** [comment]
This's really will puzzle especially the freshman using Mobius.
I'd prefer use a notion path such as `{Mobius}\build\dependency\` or `{yourself-downloaded-jars-dir}\`, etc.

**Comment by skaarthik** [comment]
Personally  I don't think it is needed. I think absolute paths make more sense and I assume those who read the doc can figure out that the path references are just for showing how to carry out somethings in Mobius.

**Comment by skaarthik** [comment]
Closing this issue for now. Reopen if needed.
