### ISSUE TITLE
Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments

### ISSUE THREAD

**Issue by shakdoesgithub** [Microsoft/Mobius#568]
Hi I'm getting this issue when I submit when using the spark-cler_2.11.-2.0.000 Preview.
Currently this is running on OSX with the following environment variables set:

export SPARK_HOME="/Users/myuser/Development/Tools/spark-2.0.0-bin-hadoop2.7"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home"
export SPARKCLR_HOME="/Users/myuser/Development/Tools/spark-clr_2.11-2.0.000-PREVIEW-1/runtime"

Funny thing is, this works great with the 1.6.2 version of both spark and the spark-clr.
But when I start to use the 2.0 apache spark, and 2.0 preview of spark-clr, it throws this error:

Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments

Here's the full output:

 ./sparkclr-submit.sh --verbose --exe apacheSpark.exe /Users/myuser/Development/Projects/apacheSpark/apacheSpark/bin/Debug/apacheSpark.sh
SPARKCLR_CLASSPATH is /Users/myuser/Development/Tools/spark-clr_2.11-2.0.000-PREVIEW-1/runtime/lib/spark-clr_2.11-2.0.000-PREVIEW-1.jar
[sparkclr-submit.sh] LAUNCH_CLASSPATH=/Users/myuser/Development/Tools/spark-clr_2.11-2.0.000-PREVIEW-1/runtime/lib/spark-clr_2.11-2.0.000-PREVIEW-1.jar:/Users/myuser/Development/Tools/spark-2.0.0-bin-hadoop2.7/jars\*
Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments
[sparkclr-submit.sh] Command to run

**Comment by skaarthik** [comment]
LAUNCH_CLASSPATH variable is not correct in the output you shared. It should be `/Users/myuser/Development/Tools/spark-2.0.0-bin-hadoop2.7/jars/*` - "/" between "jars" and "*" is missing.

Try changing the backslash to forward slash at https://github.com/Microsoft/Mobius/blob/master/scripts/sparkclr-submit.sh#L58 to see if it helps.

**Comment by skaarthik** [comment]
@shakdoesgithub Is your issue resolved? Can we close this issue?

**Comment by shakdoesgithub** [comment]
@skaarthik thanks, that was it.  I noticed this is still causing issues in AWS EMR which is based off centos.  Do you want me to create a pull request for this?

**Comment by skaarthik** [comment]
@shakdoesgithub - yes, please send PR. I am closing this issue.

**Comment by nisanth456** [comment]
I have an issue 
whenever i checking pio status
Error: Could not find or load main class org.apache.predictionio.tools.console.Console
eleastic search and HMaster running
jps -l
21012 sun.tools.jps.Jps
20934 org.apache.predictionio.tools.console.Console
20714 org.apache.hadoop.hbase.master.HMaster
20619 org.elasticsearch.bootstrap.Elasticsearch
