### ISSUE TITLE
Issue with HiveDataFrame project program

### ISSUE THREAD

**Issue by HeeJun-Lee** [Microsoft/Mobius#576]
While running HiveDataFrame example, following exception gets thrown in the HiveContext creation line.

--------------------------------------------------------------------------------------------------------------------
C:\Users\hjlee\Downloads\Mobius-master\build\runtime\scripts>sparkclr-submit.cmd --exe HiveDataFrame.exe C:\Users\hjlee\Downloads\Mobius-master\examples\Sql\HiveDataFrame\bin\Debug
[sparkclr-submit.cmd] SPARKCLR_JAR=spark-clr_2.11-2.0.000-SNAPSHOT.jar
[sparkclr-submit.cmd] LAUNCH_CLASSPATH="C:\Users\hjlee\Downloads\Mobius-master\build\runtime\lib\spark-clr_2.11-2.0.000-SNAPSHOT.jar;C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6\jars\*"
C:\WINDOWS\TEMP\spark-class-launcher-output-19426.txt을(를) 찾을 수 없습니다.
[sparkclr-submit.cmd] Command to run --name HiveDataFrame --class org.apache.spark.deploy.csharp.CSharpRunner C:\Users\hjlee\Downloads\Mobius-master\build\runtime\lib\spark-clr_2.11-2.0.000-SNAPSHOT.jar C:\Users\hjlee\Downloads\Mobius-master\examples\Sql\HiveDataFrame\bin\Debug C:\Users\hjlee\Downloads\Mobius-master\examples\Sql\HiveDataFrame\bin\Debug\HiveDataFrame.exe
C:\WINDOWS\TEMP\spark-class-launcher-output-29667.txt을(를) 찾을 수 없습니다.
[2016-10-06 14:40:07,891] [1] [INFO ] [Microsoft.Spark.CSharp.Examples.HiveDataFrameExample] - Input args is '0' ea
[2016-10-06 14:40:07,907] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService] - Spark Master is 'local[*]'
[2016-10-06 14:40:07,907] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService] - ConfigurationService runMode is LOCAL
[2016-10-06 14:40:07,907] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService+SparkCLRConfiguration] - CSharpBackend successfully read from environment variable CSHARPBACKEND_PORT -> value '53647'
[2016-10-06 14:40:07,907] [1] [INFO ] [Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy] - CSharpBackend port number to be used in JvMBridge is 53647
Try Connect Socket [IP: 127.0.0.1, Port: 53647]
[2016-10-06 14:40:07,969] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - Checking objects thread start ...
[2016-10-06 14:40:07,969] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 1, checkCount: 10
[2016-10-06 14:40:07,969] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 1 alive, used 0 ms : release garbage used 0 ms, store alive used 0 ms
[2016-10-06 14:40:07,969] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkConf] - Spark home set to C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6
[2016-10-06 14:40:07,969] [1] [INFO ] [Microsoft.Spark.CSharp.Examples.HiveDataFrameExample] - Spark Configure Initialize Success !!!!
[2016-10-06 14:40:08,893] [1] [INFO ] [Microsoft.Spark.CSharp.Examples.HiveDataFrameExample] - Spark Context Initialize Success !!!!
[2016-10-06 14:40:08,893] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Static method getSparkConfAsString failed for class org.apache.spark.sql.api.csharp.JvmBridgeUtils when called with no parameters
[2016-10-06 14:40:08,893] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] -
[2016-10-06 14:40:08,893] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Static method getSparkConfAsString failed for class org.apache.spark.sql.api.csharp.JvmBridgeUtils when called with no parameters
[2016-10-06 14:40:08,940] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] -
*******************************************************************************************************************************
   위치: Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters) 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:줄 96
*******************************************************************************************************************************

처리되지 않은 예외: System.Exception: JVM method execution failed: Static method getSparkConfAsString failed for class org.apache.spark.sql.api.csharp.JvmBridgeUtils when called with no parameters
   위치: Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters) 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:줄 144
   위치: Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallStaticJavaMethod(String className, String methodName) 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:줄 58
   위치: Microsoft.Spark.CSharp.Proxy.Ipc.SparkConfIpcProxy.GetSparkConfAsString() 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Proxy\Ipc\SparkConfIpcProxy.cs:줄 63
   위치: Microsoft.Spark.CSharp.Core.SparkConf.GetAll() 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Core\SparkConf.cs:줄 134
   위치: Microsoft.Spark.CSharp.Sql.Builder.Config(SparkConf conf) 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Sql\Builder.cs:줄 97
   위치: Microsoft.Spark.CSharp.Sql.HiveContext..ctor(SparkContext sparkContext) 파일 C:\Users\hjlee\Downloads\Mobius-master\csharp\Adapter\Microsoft.Spark.CSharp\Sql\HiveContext.cs:줄 21
   위치: Microsoft.Spark.CSharp.Examples.HiveDataFrameExample.Main(String[] args) 파일 C:\Users\hjlee\Downloads\Mobius-master\examples\Sql\HiveDataFrame\Program.cs:줄 39

C:\Users\hjlee\Downloads\Mobius-master\build\runtime\scripts>

-------------------------------------------------------------------------------------------------------------------

And 'Main' method code in program

-------------------------------------------------------------------------------------------------------------------
static void Main(string[] args)
        {
            LoggerServiceFactory.SetLoggerService(Log4NetLoggerService.Instance); //this is optional - DefaultLoggerService will be used if not set
            var logger = LoggerServiceFactory.GetLogger(typeof(HiveDataFrameExample));

            logger.LogInfo(string.Format("Input args is '{0}' ea", args.Length));
            foreach(var arg in args)
            {
                logger.LogInfo(string.Format("Input args is '{0}'", arg));
            }

            var sparkConf = new SparkConf().SetSparkHome(@"C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6");//.SetMaster("spark://10.10.0.190:7077");
            logger.LogInfo(string.Format("Spark Configure Initialize Success !!!!"));
            var sparkContext = new SparkContext(sparkConf);
            logger.LogInfo(string.Format("Spark Context Initialize Success !!!!"));

            //logger.LogInfo(string.Format("Configure Get Test !!!!"));
            //sparkConf.Set("spark.driver.memory", "2G");
            //logger.LogInfo(string.Format("Configure Get All Success !!!!"));

            var hiveContext = new HiveContext(sparkContext);
            logger.LogInfo(string.Format("Hive Context Initialize Success !!!!"));

            // please give the path to input json file
            //var jsonFilePath = args[0];
            //var peopleDataFrame = hiveContext.Read().Json(jsonFilePath);
            //logger.LogInfo(string.Format("Read Json File in Hive !!!!"));

            //const string dbName = "SampleHiveDataBaseForMobius";
            //const string tableName = "people";

            //hiveContext.Sql(string.Format("CREATE DATABASE IF NOT EXISTS {0}", dbName)); // create database if not exists
            //hiveContext.Sql(string.Format("USE {0}", dbName));
            //hiveContext.Sql(string.Format("DROP TABLE {0}", tableName)); // drop table if exists

            //peopleDataFrame.Write().Mode(SaveMode.Overwrite).SaveAsTable(tableName); // create table
            //var tablesDataFrame = hiveContext.Tables(dbName); // get all tables in database
            //logger.LogInfo(string.Format("table count in database {0}: {1}", dbName, tablesDataFrame.Count()));
            //tablesDataFrame.Show();

            //hiveContext.Sql(string.Format("SELECT * FROM {0}", tableName)).Show(); // select from table

            logger.LogInfo(string.Format("Application Close !!!!"));
        }
-------------------------------------------------------------------------------------------------------------------

Finally, my environment variable list.

-------------------------------------------------------------------------------------------------------------------
HADOOP_HOME  -> C:\Users\hjlee\Downloads\Mobius-master\build\tools\winutils
JAVA_HOME         -> C:\Program Files\Java\jdk1.8.0_101
SPARK_HOME       -> C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6
SPARKCLR_HOME -> C:\Users\hjlee\Downloads\Mobius-master\build\runtime
SPARKCLR_EXT_JARS -> C:\Users\hjlee\Downloads\Mobius-master\build\runtime\dependencies\commons-csv-1.4.jar,C:\Users\hjlee\Downloads\Mobius-master\build\runtime\dependencies\spark-csv_2.10-1.4.0.jar,C:\Users\hjlee\Downloads\Mobius-master\build\runtime\dependencies\spark-streaming-kafka-0-8-assembly_2.11-2.0.0.jar,C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6\jars\datanucleus-api-jdo-3.2.6.jar,C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6\jars\datanucleus-core-3.2.10.jar,C:\Users\hjlee\Downloads\Mobius-master\build\tools\spark-2.0.0-bin-hadoop2.6\jars\datanucleus-rdbms-3.2.9.jar
-------------------------------------------------------------------------------------------------------------------

I think that exception is occured when execute 'getAll' method in 'sparkConf'

Please help me resolving this... Thanks!

**Comment by skaarthik** [comment]
@HeeJun-Lee Hive functionality was broken in Mobius during Spark 2.0 upgrade. Fix is on the way. I will post a note when the fix is ready. In the meantime, you could try using 1.6.* versions of Mobius with Hive.

**Comment by HeeJun-Lee** [comment]
First, thanks for apply.

And I try to run sample methods below command.

-------------------------------------------------------------------------------------------------------------
sparkclr-submit.cmd --jars C:\Users\hjlee\Downloads\Mobius-master\build\localmode\..\runtime\dependencies\spark-csv_2.10-1.4.0.jar,C:\Users\hjlee\Downloads\Mobius-master\build\localmode\..\runtime\dependencies\commons-csv-1.4.jar --exe SparkCLRSamples.exe C:\Users\hjlee\Downloads\Mobius-master\build\localmode\..\runtime\samples spark.local.dir C:\Users\hjlee\Downloads\Mobius-master\build\localmode\..\runtime\Temp sparkclr.sampledata.loc C:\Users\hjlee\Downloads\Mobius-master\build\localmode\..\runtime\data
-------------------------------------------------------------------------------------------------------------

Below result log.

-------------------------------------------------------------------------------------------------------------
Successfully completed samples:
    SqlContextNewSessionSample (category: default), duration=00:00:00.0023425
    SqlContextGetOrCreateSample (category: default), duration=00:00:00.0002280
    SparkContextUnionSample (category: default), duration=00:00:00.0547659
    SparkContextSample (category: default), duration=00:00:00.0101435
    SparkContextHadoopConfigurationSample (category: default), duration=00:00:00.0034370
    SparkContextBroadcastSample (category: default), duration=00:00:00.4850135
    SparkContextAccumulatorSample (category: default), duration=00:00:01.3596779
    RDDZipWithUniqueIdSample (category: default), duration=00:00:00.5898090
    RDDZipWithIndexSample (category: default), duration=00:00:01.1413656
    RDDZipSample (category: default), duration=00:00:00.0394447
    RDDWordCountSample (category: default), duration=00:00:01.1999504
    RDDUnionSample (category: default), duration=00:00:00.0191092
    RDDTreeReduceSample (category: default), duration=00:00:02.4457491
    RDDTreeAggregateSample (category: default), duration=00:00:00.2381181
    RDDTopSample (category: default), duration=00:00:00.4205277
    RDDToLocalIteratorSample (category: default), duration=00:00:00.2436218
    RDDToDebugStringSample (category: default), duration=00:00:00.0090889
    RDDTakeSampleSample (category: default), duration=00:00:00.0968270
    RDDTakeSample (category: default), duration=00:00:00.2485618
    RDDTakeOrderedSample2 (category: default), duration=00:00:00.4433959
    RDDTakeOrderedSample (category: default), duration=00:00:00.4204379
    RDDSubtractSample (category: default), duration=00:00:01.2371671
    RDDStringCollectionSample (category: default), duration=00:00:00.3978597
    RDDSetNameSample (category: default), duration=00:00:00.0020372
    RDDSerializableObjectCollectionSample (category: default), duration=00:00:00.5891251
    RDDSaveAsTextFileSample (category: default), duration=00:00:00.6625592
    RDDSampleSample (category: default), duration=00:00:00.0119947
    RDDRepartitionSample (category: default), duration=00:00:01.2503237
    RDDReduceSample (category: default), duration=00:00:00.2591522
    RDDRandomSplitSample (category: default), duration=00:00:00.0357023
    RDDMinSample (category: default), duration=00:00:00.4206753
    RDDMaxSample (category: default), duration=00:00:00.4169967
    RDDMapFilterSample (category: default), duration=00:00:00.8425695
    RDDKeyBySample (category: default), duration=00:00:00.2531839
    RDDJoinSample (category: default), duration=00:00:02.6870990
    RDDIsEmptySample (category: default), duration=00:00:00.2058201
    RDDIntersectionSample (category: default), duration=00:00:01.2335954
    RDDIntCollectionSample (category: default), duration=00:00:00.5972014
    RDDGroupBySample (category: default), duration=00:00:00.5264888
    RDDGlomSample (category: default), duration=00:00:00.4374892
    RDDForeachSample (category: default), duration=00:00:00.2217386
    RDDForeachPartitionSample (category: default), duration=00:00:00.2223952
    RDDFoldSample (category: default), duration=00:00:00.2436278
    RDDFirstSample (category: default), duration=00:00:00.2696742
    RDDDistinctSample (category: default), duration=00:00:00.5087965
    RDDCountByValueSample (category: default), duration=00:00:00.9695565
    RDDCombineBySample (category: default), duration=00:00:03.3201596
    RDDCoalesceSample (category: default), duration=00:00:00.8386241
    RDDCheckpointSample (category: default), duration=00:00:00.2810663
    RDDCartesianSample (category: default), duration=00:00:00.0180365
    RDDAggregateSample (category: default), duration=00:00:00.2427832
    PiSample (category: default), duration=00:00:04.6883935
    PairRDDValuesSample (category: default), duration=00:00:00.2340602
    PairRDDSubtractByKeySample (category: default), duration=00:00:02.3589133
    PairRDDSortByKeySample (category: default), duration=00:00:04.0846650
    PairRDDRightOuterJoinSample (category: default), duration=00:00:01.7772695
    PairRDDReduceByKeySample (category: default), duration=00:00:00.8037237
    PairRDDReduceByKeyLocallySample (category: default), duration=00:00:00.8616000
    PairRDDPartitionBySample (category: default), duration=00:00:01.2021655
    PairRDDMapValuesSample (category: default), duration=00:00:00.4100778
    PairRDDLookupSample (category: default), duration=00:00:03.7846388
    PairRDDLeftOuterJoinSample (category: default), duration=00:00:01.7526383
    PairRDDKeysSample (category: default), duration=00:00:00.2230081
    PairRDDJoinSample (category: default), duration=00:00:01.2399671
    PairRDDGroupWithSample2 (category: default), duration=00:00:02.8059782
    PairRDDGroupWithSample (category: default), duration=00:00:01.7660290
    PairRDDGroupByKeySample (category: default), duration=00:00:00.8676094
    PairRDDFullOuterJoinSample (category: default), duration=00:00:02.3461953
    PairRDDFoldByKeySample (category: default), duration=00:00:00.8762590
    PairRDDFlatMapValuesSample (category: default), duration=00:00:00.4175729
    PairRDDCountByKeySample (category: default), duration=00:00:00.8184909
    PairRDDCombineByKeySample (category: default), duration=00:00:00.8214691
    PairRDDCollectAsMapSample (category: default), duration=00:00:00.0148168
    PairRDDAggregateByKeySample (category: default), duration=00:00:00.8605370
    DoubleRDVarianceSample (category: default), duration=00:00:00.4002016
    DoubleRDDSumSample (category: default), duration=00:00:00.3968796
    DoubleRDDStdevSample (category: default), duration=00:00:00.4136272
    DoubleRDDStatsSample (category: default), duration=00:00:00.3984247
    DoubleRDDSampleVarianceSample (category: default), duration=00:00:00.4298874
    DoubleRDDSampleStdevSample (category: default), duration=00:00:00.4133462
    DoubleRDDMeanSample (category: default), duration=00:00:00.4403082
Failed samples:
    SSTableSample (category: default), duration=00:00:02.5336634
    SSSqlSample (category: default), duration=00:00:00.0628437
    SSShowSchemaSample (category: default), duration=00:00:00.0612515
    SSNewSessionSample (category: default), duration=00:00:00.0784513
    SSDropTableSample (category: default), duration=00:00:00.0570513
    SSDataFrameSample (category: default), duration=00:00:00.0568680
    SSCreateDataFrameSample (category: default), duration=00:00:00.1483262
    SqlContextTempTableSample (category: default), duration=00:00:00.0496390
    SqlContextTablesSample (category: default), duration=00:00:00.0486063
    SqlContextReadParquetSample (category: default), duration=00:00:00.0429646
    SqlContextReadJsonWithOptionSample (category: default), duration=00:00:00.0519195
    SqlContextReadJsonSample (category: default), duration=00:00:00.0420555
    SqlContextCreateDataFrameSample2 (category: default), duration=00:00:00.0541157
    SqlContextCreateDataFrameSample (category: default), duration=00:00:00.0152542
    SqlContextClearCacheTableSample (category: default), duration=00:00:00.0391322
    SqlContextCacheAndUncacheTableSample (category: default), duration=00:00:00.0398854
    DFWriteToParquetSampleWithAppendMode (category: default), duration=00:00:00.0352691
    DFWriteToParquetSample (category: default), duration=00:00:00.0255405
    DFWriteToJsonSample (category: default), duration=00:00:00.0352354
    DFWithColumnSample (category: default), duration=00:00:00.0428279
    DFWithColumnRenamedSample (category: default), duration=00:00:00.0273710
    DFUnpersistSample (category: default), duration=00:00:00.0282813
    DFUnionAllSample (category: default), duration=00:00:00.0330540
    DFTextFileLoadDataFrameSample (category: default), duration=00:00:00.0679520
    DFTextFileJoinTempTableSample (category: default), duration=00:00:00.0709906
    DFTextFileJoinTableDSLSample (category: default), duration=00:00:00.0410185
    DFTakeSample (category: default), duration=00:00:00.0265542
    DFSubtractSample (category: default), duration=00:00:00.0277679
    DFSortWithinPartitionsSample (category: default), duration=00:00:00.0270582
    DFSortSample (category: default), duration=00:00:00.0286410
    DFShowSchemaSample (category: default), duration=00:00:00.0263310
    DFSelectSample (category: default), duration=00:00:00.0383071
    DFSchemaSample (category: default), duration=00:00:00.0290782
    DFSaveSample (category: default), duration=00:00:00.0259863
    DFSaveAsParquetFileSample (category: default), duration=00:00:00.0280861
    DFSampleSample (category: default), duration=00:00:00.0261264
    DFRollupSample (category: default), duration=00:00:00.0255963
    DFReplaceSample (category: default), duration=00:00:00.0264924
    DFRepartitionSample2 (category: default), duration=00:00:00.0258139
    DFRepartitionSample (category: default), duration=00:00:00.0264044
    DFRegisterTableSample (category: default), duration=00:00:00.0276215
    DFRddSample (category: default), duration=00:00:00.0310259
    DFRandomSplitSample (category: default), duration=00:00:00.0279163
    DFProjectionFilterUDFSample (category: default), duration=00:00:00.0536830
    DFProjectionFilterDSLSample (category: default), duration=00:00:00.0311998
    DFPersistSample (category: default), duration=00:00:00.0242265
    DFNaReplaceSample (category: default), duration=00:00:00.0326021
    DFNaFillSample (category: default), duration=00:00:00.0294228
    DFNaDropSample (category: default), duration=00:00:00.0297852
    DFMapSample (category: default), duration=00:00:00.0267465
    DFMapPartitionsSample (category: default), duration=00:00:00.0254049
    DFLimitSample (category: default), duration=00:00:00.0275155
    DFJoinSample (category: default), duration=00:00:00.0259380
    DFJoinMultiColSample (category: default), duration=00:00:00.0252301
    DFIsLocalSample (category: default), duration=00:00:00.0282200
    DFIntersectSample (category: default), duration=00:00:00.0247730
    DFHeadSample (category: default), duration=00:00:00.0245165
    DFGroupDataOperationSample (category: default), duration=00:00:00.0268367
    DFGetSchemaJsonSample (category: default), duration=00:00:00.0273821
    DFFreqItemsSample (category: default), duration=00:00:00.0279163
    DFForeachSample (category: default), duration=00:00:00.0248722
    DFForeachPartitionSample (category: default), duration=00:00:00.0257881
    DFForeachnSampleWithAccumulator (category: default), duration=00:00:00.0383771
    DFFlatMapSample (category: default), duration=00:00:00.0268508
    DFFirstSample (category: default), duration=00:00:00.0242641
    DFFillNaSampleWithDict (category: default), duration=00:00:00.0275013
    DFFillNaSample (category: default), duration=00:00:00.0281434
    DFDTypesSample (category: default), duration=00:00:00.0272150
    DFDropSample (category: default), duration=00:00:00.0310364
    DFDropNaSample (category: default), duration=00:00:00.0311655
    DFDropDuplicatesSample (category: default), duration=00:00:00.0331282
    DFDistinctSample (category: default), duration=00:00:00.0417139
    DFDescribeSample (category: default), duration=00:00:00.0279286
    DFCubeSample (category: default), duration=00:00:00.0261180
    DFCrosstabSample (category: default), duration=00:00:00.0306463
    DFCovSample (category: default), duration=00:00:00.0262216
    DFCorrSample (category: default), duration=00:00:00.0347988
    DFConversionSample (category: default), duration=00:00:00.0410188
    DFColumnsSample (category: default), duration=00:00:00.0283664
    DFCollectSample (category: default), duration=00:00:00.0296169
    DFCoalesceSample (category: default), duration=00:00:00.0290857
    DFCacheSample (category: default), duration=00:00:00.0274649
    DFAliasSample (category: default), duration=00:00:00.0292380
    DFAggregateDSLSample (category: default), duration=00:00:00.0290650
    CatalogSample (category: default), duration=00:00:00.0068570
-------------------------------------------------------------------------------------------------------------

many sample codes are failed.

Is failed cause same? (by Spark 2.0 version)

**Comment by HeeJun-Lee** [comment]
Thank you.

Secondary problem is solved.

**Comment by skaarthik** [comment]
@HeeJun-Lee the issue with HiveDataFrame example is fixed in https://github.com/Microsoft/Mobius/commit/edd7b7fd8b73190dcf5c254ae1342fda43dee835.

Check out using Mobius with Hive using the SparkSession and deprecated HiveContext API in this PR (https://github.com/skaarthik/Mobius/blob/34567724738ce095c268c8e1408a48504cb440bc/examples/Sql/HiveDataFrame/Program.cs). You can build Mobius from master branch to use this Hive example. This PR will be merged to master branch after the latest code from master branch (including SparkSession) is included in the next PREVIEW release (which will be referenced in packages.config of the example).
