### ISSUE TITLE
spark machine learning

### ISSUE THREAD

**Issue by jokerruslan** [Microsoft/Mobius#588]
Hello,friends.
Can I use spark machine learning through Mobius? I can not find this info. Where I can read more if it is possible

**Comment by dwnichols** [comment]
Hi, 

I believe MLlib is supported but SparkML is not supported. There is an issue opened to add SparkML support: #554.

**Comment by jokerruslan** [comment]
What is may difference between mllib and sparkml?

**Comment by dwnichols** [comment]
The spark docs should answer your questions. The main difference is MLlib was written on top of RDDs whereas SparkML is being written on top of DataFrames.

http://spark.apache.org/docs/latest/ml-guide.html

**Comment by skaarthik** [comment]
@jokerruslan - At present none of the Spark's ML APIs are available in Mobius. It is something Mobius project is considering to add if there is demand (the issue pointed out by @dwnichols is to track that).

**Comment by skaarthik** [comment]
Closing this issue as #554 is open
