### ISSUE TITLE
Compile to JVM ?

### ISSUE THREAD

**Issue by grecinto** [Microsoft/Mobius#594]
Hi,

Could it be a good time to finally support compilation of c#/f# to JVM?

There are quite few big wins if this is the case. Example, there will be no need for mono and windows binaries. c#/f# will be like Java and Scala in "perceived" performance from the engineers.

Thanks

**Comment by skaarthik** [comment]
@grecinto - do you have any specific recommendation on how to make it happen? What tools/frameworks can be successfully employed for this?

**Comment by grecinto** [comment]
It looks like a Microsoft c# compiler team task, to support generation of JVM bytecode as additional option aside from .net bytecode.

I have no clue how Satya Nadella will think about it, but at this time, making c# as a JVM language seems the best approach to keep Microsoft relevant in the Open Source world.

Thanks

**Comment by skaarthik** [comment]
@grecinto thanks for your suggestion. It would be great to get C# code can run in JVM but I doubt that any production-ready frameworks available out there for this scenario. Considering that the scope of what you are suggesting is well beyond the scope of Mobius project, I am closing this issue. Feel free to reopen it if you have any suggestions on what could be done in Mobius if someone is interested in using any existing 3rd party framework or tool to run C# code in JVM.
