### ISSUE TITLE
Is Mobius C# assembly supported in .NET CORE project ?

### ISSUE THREAD

**Issue by ramkumarravy** [Microsoft/Mobius#601]
Hi,

I'd like to know, whether Mobius C# assembly (Microsoft.Spark.CSharp.Adapter.dll) is supported in .NET CORE project. I've tried migrating the classes of existing .NET Framework 4.5 - Adapter library to .NET CORE class library, but many classes were not supported in CORE project. So, could you please let me know any solution for this ?

Thanks,
Ramkumar

**Comment by skaarthik** [comment]
Ramkumar - Mobius has not been ported to .NET Core yet and it does not work in .NET Core precisely for the reasons you stated in your mail. I assume you want .NET Core support to use Mobius in non-Windows environment. Consider using Mono if that is the case.

**Comment by abatishchev** [comment]
@ramkumarravy  it's Core by the way, not CORE, it's not an abbreviation

**Comment by skaarthik** [comment]
@ramkumarravy - closing this issue as the question is answered. Feel free to rephrase the title of the issue and reopen if needed.
