### ISSUE TITLE
Unable to launch sparkclr-shell on Spark 1.6.2

### ISSUE THREAD

**Issue by Aaronontheweb** [Microsoft/Mobius#603]
Wrote the following script to install **all** of the dependencies needed to run Mobius automatically, including the JDK and Mobius itself: https://github.com/petabridge/spark-installer-windows/blob/master/installers/1.6.2/install-spark1.6.2.ps1

Works great thus far. Can launch the Scala Spark shell and connect to my DSE instances, no problem.

I ran into the following hiccup when attempting to launch the Mobius REPL, however:

`Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments`

Seems like a common issue around here, but I did some digging and noticed the following:

```
C:\Mobius\spark-clr-1.6.2\runtime>"C:\Program Files\Java\jdk1.8.0_112\bin\java" -cp ";C:\Mobius\spark-clr-1.6.2\runtime\lib\spark-clr_2.10-1.6.200.jar" org.apache.spark.launcher.SparkCLRSubmitArguments --name MobiusShell  --exe Repl.exe C:\Mobius\spark-clr-1.6.2\runtime\scripts\..\repl  1>C:\Users\aaron\AppData\Local\Temp\spark-class-launcher-output-31809.txt
```

That's the commandline argument being using to launch the REPL, in response to the following command I typed:

```
C:\Mobius\spark-clr-1.6.2\runtime>.\scripts\sparkclr-shell.cmd
```

*Something* isn't getting picked up on the CLASSPATH correctly, by for the life of me I can't figure it out - especially given that the path being used on the `-cp` flag is the correct one. Any ideas?

**Comment by skaarthik** [comment]
Classpath should be of the format `%SPARK_HOME%\lib\spark-assembly-1.6.2-hadoop2.6.0.jar;%SPARKCLR_HOME%\lib\spark-clr_2.10-1.6.200.jar`.

The first part is missing in the statement you copied above and cp starts with `;`. Make sure that you have Spark

**Comment by Aaronontheweb** [comment]
@skaarthik yep, SPARK_HOME is set to C:\Spark\spark-1.6.2-bin-hadoop2.6.0 and the spark-assembly-1.6.2-hadoop2.6.0.jar is in the lib sub-folder.

**Comment by skaarthik** [comment]
If that is the case, I do not know what's going on. The classpath is set at https://github.com/Microsoft/Mobius/blob/branch-1.6/scripts/sparkclr-submit.cmd#L47. Try to echo `LAUNCH_CLASSPATH` to find out what is assigned to it.

**Comment by Aaronontheweb** [comment]
Think I found the issue: https://github.com/Microsoft/Mobius/blob/branch-1.6/scripts/sparkclr-submit.cmd#L32

Here's what I got on my console when I use `echo LAUNCH_CLASSPATH`: %%d;C:\Mobius\spark-clr-1.6.2\runtime\lib\spark-clr_2.10-1.6.200.jar

**Comment by Aaronontheweb** [comment]
Oh snap! Found the issue. Not Mobius' fault. PEBKAC. Issue is I had an extra zero in the name of the SPARK_HOME folder.
