### ISSUE TITLE
Running Word Count example in Visual Studio debug mode

### ISSUE THREAD

**Issue by im281** [Microsoft/Mobius#624]
I can run the wordcount example using the following commands:

sparkclr-submit.cmd --exe SparkClrWordCount.exe C:\Users\Owner\OneDrive\Source\Repos\Mobius-master\examples\Batch\WordCount\bin\Debug file:///C:/Users/Owner/OneDrive/Source/Repos/Mobius-master/examples/testfile.txt

However, when I try to run in debug mode in visual studio I get this error:
{"Value cannot be null.\r\nParameter name: path1"}

Also how do I run multiple files from a directory?

The following example only reads one file?

var lines = sparkContext.TextFile(args[0]);
                var counts = lines
                    .FlatMap(x =>  x.Split(' '))
                    .Map(w => new KeyValuePair<string, int>(w, 1))
                    .ReduceByKey((x, y) => x + y);

                foreach (var wordcount in counts.Collect())
                {
                    Console.WriteLine("{0}: {1}", wordcount.Key, wordcount.Value);
                }

**Comment by Mrsevic** [comment]
Either change the code or run it in command window.

**Comment by dwnichols** [comment]
@Mrsevic is correct. 

You need to run the program within the command prompt, outlined [here](https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md#running-in-local-mode-dev-environment). The [debugging docs](https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#debug-mode) also may be helpful depending on your goals.

As for accepting more than one file, you'd need to make the appropriate code changes to achieve this. Currently the code accepts one file as an argument.
`var lines = sparkContext.TextFile(args[0]);`

Let me know if that helps.

**Comment by im281** [comment]
Great thanks! It works

**Comment by dwnichols** [comment]
You're welcome.
