### ISSUE TITLE
Static method collectAndServe error

### ISSUE THREAD

**Issue by Mrsevic** [Microsoft/Mobius#626]
I have CsharpWorkPath set up as well as the port, I have tried with the version from my local /bin/debug folder and the driver version in  the C:\sparkCLR\runtime\bin. I am trying to run Pi program.
The exact error is:
{"JVM method execution failed: Static method collectAndServe failed for class org.apache.spark.api.python.PythonRDD when called with 1 parameters ([Index=1, Type=JvmObjectReference, Value=13], )"}
I have also tried with the temp parameter but it does not do any good as far as I have seen. I have completely disabled my AV software and I have also disabled MS Defender.
Thanks

**Comment by dwnichols** [comment]
Hi @Mrsevic. This error is covered in the [troubleshooting documentation](https://github.com/Microsoft/Mobius/blob/master/notes/troubleshooting-mobius.md). Helpfully that helps.

**Comment by Mrsevic** [comment]
As already noted in original post I have already set up that parameter.

**Comment by dwnichols** [comment]
Okay, I must have missed that.

Can you provide steps to reproduce this error? Do the Mobius examples run successfully?

**Comment by skaarthik** [comment]
@Mrsevic - are you getting this error only in debug mode?

**Comment by Mrsevic** [comment]
Hi Kaarthik. Thank you for your response. No I am afraid that I am getting the error also in production, release mode.

**Comment by dwnichols** [comment]
@Mrsevic : are you running the example in local mode? You can swap to local mode by changing your environment variables to point to the Mobius build directory. For example:
```
set SPARKCLR_EXT_JARS=C:\Code\Mobius\build\localmode\..\runtime\dependencies\spark-csv_2.10-1.4.0.jar,C:\Code\Mobius\build\localmode\..\runtime\dependencies\commons-csv-1.4.jar
set SPARKCLR_HOME=C:\Code\Mobius\build\localmode\..\runtime
set SPARK_HOME=C:\Code\Mobius\build\localmode\..\tools\spark-2.0.0-bin-hadoop2.6
set HADOOP_HOME=C:\Code\Mobius\build\localmode\..\tools\winutils
```

If not, can you swap to local mode and try to run it? Also, if you're not running local mode, you'll need to verify that the spark version you are running against is the same as your Mobius build. Currently, the master branch supports spark version 2.0.2.

**Comment by skaarthik** [comment]
@Mrsevic - +1 on suggestion from @dwnichols . Try running the example for the Mobius release and report back the result instead of building the example in your machine.

**Comment by Mrsevic** [comment]
@dwnichols @skaarthik  Thank you for your support.

I have checked again all the version and yes I have spark 2.0.2 and all the other necessary prerequisites. 

I do want to run the examples again using Standalone Cluster Client mode, but I have tried with local mode as well.

In order to  do this you have to build solution first as stated in documentation. Everything was successfully built.

In client mode it seems that example is executed successfully with the following command:
sparkclr-submit.cmd --master local[*] --total-executor-cores 2 --exe SparkClrPi.exe C:\mobius-driver\Mobius-master\examples\Batch\pi\bin\Debug
When I add debug parameter however good old error returns again but this time with another value of 15 and sometimes 21 instead of 13. Probably it is the same error as it was already.

As for the suggestion of running in local mode when I build solution I do not get any spark or winutils folder. I do have winutils exe generated and some runtime(although in different folder).

**Comment by dwnichols** [comment]
The downloading of some dependencies is within the run samples scripts. You can find the samples script within the Mobius project: .\build\localmode\RunSamples.cmd

**Comment by Mrsevic** [comment]
Thanks. 

I have set these variables like you have said:
set SPARKCLR_EXT_JARS=C:\mobius-driver\Mobius-master\build\runtime\dependencies\commons-csv-1.4.jar, C:\mobius-driver\Mobius-master\build\runtime\dependencies\spark-csv_2.10-1.4.0.jar, C:\mobius-driver\Mobius-master\build\runtime\dependencies\spark-streaming-kafka-0-8-assembly_2.11-2.0.0.jar

set SPARKCLR_HOME=C:\mobius-driver\Mobius-master\build\runtime

set SPARK_HOME=C:\mobius-driver\Mobius-master\build\tools\spark-2.0.2-bin-hadoop2.6

set HADOOP_HOME=C:\mobius-driver\Mobius-master\build\tools\winutils

Run samples work fine but as I want to do some debug this time around  I get the debug error at the very first step:
An unhandled exception of type 'System.Exception' occurred in Microsoft.Spark.CSharp.Adapter.dll

Additional information: JVM method execution failed: Constructor failed for class org.apache.spark.SparkContext when called with 1 parameters ([Index=1, Type=JvmObjectReference, Value=15], )

**Comment by Mrsevic** [comment]
You can close this issue it is irrelevant to debug, it is important that the sample runs.

**Comment by dwnichols** [comment]
Closing as per requested.
