### ISSUE TITLE
Cannot build or debug on Windows 7 X64

### ISSUE THREAD

**Issue by Mrsevic** [Microsoft/Mobius#628]
First issue is in building the project. I get the following error whilst trying to build with either VS 2017 or VS 2015. 

Add-Type : Cannot add type. The assembly 'system.io.compression.filesystem' cou
ld not be found.
At C:\Mobius-master\build\localmode\downloadtools.ps1:595 char:9
+ Add-Type <<<<  -assembly "system.io.compression.filesystem"
    + CategoryInfo          : ObjectNotFound: (system.io.compression.filesyste
   m:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands
   .AddTypeCommand

Add-Type : Cannot add type. One or more required assemblies are missing.
At C:\Mobius-master\build\localmode\downloadtools.ps1:595 char:9
+ Add-Type <<<<  -assembly "system.io.compression.filesystem"
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationExc
   eption
    + FullyQualifiedErrorId : ASSEMBLY_LOAD_ERRORS,Microsoft.PowerShell.Comman
   ds.AddTypeCommand

The second error is that debugging won't even start on the machine when variables are set to release mode. Sparkclr-submit is running on the back side with debug enabled.

**Comment by skaarthik** [comment]
What versions of PowerShell and .NET are you using?

**Comment by Mrsevic** [comment]
I have been using PowerShell 2. After upgrading problem is fixed but I cannot build solution due to incompatibility with VS 2017 RC probably. 

I installed VS 2015 afterwards but it seems that there are problems running developer command windows because of some issues with path. I'll try reinstalling and building again.

I can finally connect to the debugger, run the solution in release mode but still no luck with debugging.

**Comment by skaarthik** [comment]
> I can finally connect to the debugger, run the solution in release mode but still no luck with debugging

I am not sure what you mean by this. Can you provide details?

BTW, you can only debug driver program when you step through the driver code. Worker-side execution may involve launching of CSharpWorker.exe (from JVM) and you cannot step into that code by debugging driver program.

**Comment by Mrsevic** [comment]
It is essentially the same issue as before(: Static method collectAndServe failed for class org.apache.spark.api.python.PythonRDD)and now in my Kafka processing program I get the error on 

Honestly I just want to debug some of mine samples and my new Kafka project. I have no intentions into debugging Mobius core itself. I have tried local mode as well it is only working on release not in debug mode.

You can close this issue on building on Win 7 X64, probably it cannot build on VS 2017 RC.

Thanks

**Comment by skaarthik** [comment]
Maybe there should be a new issue to track Mobius support in VS 2017. The issue in screenshot seems like a different one. Something might have changed in KafkaUtilsPythonHelper resulting in this failure. I will investigate and get back on this.

**Comment by Mrsevic** [comment]
Could you be so kind and name the versions of zookeeper and kafka that you have used in past, as well as the versions of mobius driver, spark and hadoop?

Thanks

**Comment by skaarthik** [comment]
I have used Kafka 0.8 with Mobius and the [jar that is released as dependency](https://github.com/Microsoft/Mobius/blob/master/build/localmode/downloadtools.ps1#L381) is for this version of Kafka.

**Comment by Mrsevic** [comment]
Could you please close this issues so I can open the new one?

**Comment by dwnichols** [comment]
I assume this is no longer an issue. Closing as per requested.
