### ISSUE TITLE
Error whilst building on Windows 10

### ISSUE THREAD

**Issue by Mrsevic** [Microsoft/Mobius#634]
In the past I have build the project on my Windows 10 + VS 2015 configuration with absolute zero problems. However recently I encounter these errors:
http://prntscr.com/ejv2d2
I really do not know where did this error came out from. 

Thanks

**Comment by dwnichols** [comment]
@Mrsevic : that looks to be a problem with one of the build dependencies. The direct download link changed. I have updated the build script. Can you pull the latest and try again?

**Comment by Mrsevic** [comment]
I am getting the same mistake I am afraid. It was building before, only thing I did was to install maven on my machine and setting up envieromental and user variables for it. Here's the full log:

 Directory of C:\Mobius-2.0.200\build

19-Mar-17  07:06 PM    <DIR>          .
19-Mar-17  07:06 PM    <DIR>          ..
28-Jan-17  08:19 PM             7,784 Build.cmd
28-Jan-17  08:19 PM             4,127 build.sh
28-Jan-17  08:19 PM             1,321 copyjar.ps1
19-Mar-17  07:06 PM    <DIR>          data
19-Mar-17  07:06 PM    <DIR>          localmode
               3 File(s)         13,232 bytes
               4 Dir(s)   8,324,825,088 bytes free

C:\Mobius-2.0.200\build>Build.cmd
VisualStudioVersion = "14.0"
[downloadtools.Download-File] Start downloading http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=tartool&DownloadId=79064&FileTime=128946542158770000&Build=21031 to C:\Mobius-2.0.200\build\tools\TarTool.zip ...

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Web.Download...                 NotStarted    False                                ...
2      Web.Download...                 NotStarted    False                                ...
[downloadtools.Download-File] Download completed. Time taken: 4 seconds
[downloadtools.Unzip-File] Extracting C:\Mobius-2.0.200\build\localmode\..\tools\TarTool.zip to C:\Mobius-2.0.200\build\localmode\..\tools ...
Exception calling "OpenRead" with "1" argument(s): "End of Central Directory record could not be found."
At C:\Mobius-2.0.200\build\localmode\downloadtools.ps1:160 char:5
+     $entries = [IO.Compression.ZipFile]::OpenRead($zipFile).Entries
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidDataException

Exception calling "ExtractToFile" with "3" argument(s): "Value cannot be null.
Parameter name: source"
At C:\Mobius-2.0.200\build\localmode\downloadtools.ps1:166 char:13
+             [IO.Compression.ZipFileExtensions]::ExtractToFile($_, $ta ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

[downloadtools.Unzip-File] Extraction completed. Time taken: 637 milliseconds
[downloadtools.Download-File] Start downloading http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven
-3.3.9-bin.tar.gz to C:\Mobius-2.0.200\build\tools\apache-maven-3.3.9-bin.tar.gz ...
3      Web.Download...                 NotStarted    False                                ...
4      Web.Download...                 NotStarted    False                                ...
[downloadtools.Download-File] Download completed. Time taken: 8 seconds
[downloadtools.Untar-File] Extracting C:\Mobius-2.0.200\build\localmode\..\tools\apache-maven-3.3.9-bin.tar.gz to C:\Mobius-2.0.200\build\localmode\..\tools ...
& : The term 'C:\Mobius-2.0.200\build\localmode\..\tools\TarTool.exe' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:3
+ & "C:\Mobius-2.0.200\build\localmode\..\tools\TarTool.exe" C:\Mobius- ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Mobius-2.0.2...ols\TarTool.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[downloadtools.Untar-File] Extraction completed. Time taken: 48 milliseconds
[downloadtools.Download-File] Start downloading http://dist.nuget.org/win-x86-commandline/latest/nuget.exe to C:\Mobius-2.0.200\build\tools\nuget.exe ...
5      Web.Download...                 NotStarted    False                                ...
6      Web.Download...                 NotStarted    False                                ...
[downloadtools.Download-File] Download completed. Time taken: 6 seconds
[downloadtools.Download-File] Start downloading https://github.com/MobiusForSpark/winutils/blob/master/hadoop-2.6.0/bin/winutils.exe?raw=true to C:\Mobius-2.0.200\build\tools\winutils\bin\winutils.exe ...
7      Web.Download...                 NotStarted    False                                ...
8      Web.Download...                 NotStarted    False                                ...
[downloadtools.Download-File] Download completed. Time taken: 4 seconds


SPARKCLR_HOME=C:\Mobius-2.0.200\build\runtime
Assemble Mobius Scala components

Error: M2_HOME is set to an invalid directory.
M2_HOME = "C:\Mobius-2.0.200\build\localmode\..\tools\apache-maven-3.3.9"
Please set the M2_HOME variable in your environment to match the
location of the Maven installation

        1 file(s) copied.
[patchpom.ps1] updated pom.xml
        1 file(s) copied.

Error: M2_HOME is set to an invalid directory.
M2_HOME = "C:\Mobius-2.0.200\build\localmode\..\tools\apache-maven-3.3.9"
Please set the M2_HOME variable in your environment to match the
location of the Maven installation

        1 file(s) copied.
Build Mobius Scala components failed, stop building.

**Comment by dwnichols** [comment]
Hi, it looks like you haven't pulled the latest changes. From the output, the build is still attempting to download TarTool build 21031, when it should be 21046. This is the latest [change](https://github.com/Microsoft/Mobius/commit/a402cb4471d9f35efa71b1ec690f473226498569) you're missing, which is on master.

`[downloadtools.Download-File] Start downloading http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=tartool&DownloadId=79064&FileTime=128946542158770000&Build=21031 to C:\Mobius-2.0.200\build\tools\TarTool.zip`

**Comment by Mrsevic** [comment]
Some cache issues I guess. Everything works flawlessly now, thanks. 

I've seen that error was related to corrupt file and I've tried replacing, with no luck though.

**Comment by dwnichols** [comment]
Glad that solved the issue.
