### ISSUE TITLE
Not able to Run sparkclr-shell or sparkclr-submit.cmd?

### ISSUE THREAD

**Issue by jayprajapati857** [Microsoft/Mobius#637]
Hello,
I am trying to run sparckclr-shell and sparckclr-submit.cmd both but i am not getting any error or any output how do i know there is any error or its running??
i am begginer to Mobius. can anyone help me to run mobius on my machine?
i tried it on windows 7 with visual studio 2015 community and also try with latest preview release but still doesnt showing any error or any output
Thanks

**Comment by dwnichols** [comment]
@jayprajapati857 : can you verify that you have been able to build and run the Mobius samples?

`./build/Build.cmd
./build/localmode/RunSamples.cmd`

**Comment by jayprajapati857** [comment]
@dwnichols : i am trying to build but i got an Exception for "Open-read" and "ExtractToFile" because when i am building mobius from Mobius\build\Build.cmd the files are downloaded and in this files one file in tools/TarTool.zip is broken there for the build is not succeed.
So i downloaded a Preview version spark-clr_2.11-2.0.200 and then setting all environment variables i try to access sparkclr-shell but there is no response. there is not even any error or any output.
can u suggest me how to start with it and run samples.
Thanks

**Comment by dwnichols** [comment]
Hi @jayprajapati857 : It looks like the build number for one of our dependencies has changed. I've updated the build script. Once it passes the tests, can you please pull the latest changes and try again? Thanks.

**Comment by dwnichols** [comment]
As for running `sparkclr-shell.cmd`, can you please provide your environment variables for:

```
SPARKCLR_EXT_JARS
SPARKCLR_HOME
SPARK_HOME
JAVA_HOME
HADOOP_HOME
```

Also, provide a screenshot or copy/paste the text from your terminal. Thanks

**Comment by jayprajapati857** [comment]
Hello @dwnichols: Thanks its working now and, succeed to build and samples are also running.

**Comment by dwnichols** [comment]
Great to hear!
