### ISSUE TITLE
running-mobius-app documentation incorrect

### ISSUE THREAD

**Issue by kmleow** [Microsoft/Mobius#644]
```/blob/master/notes/running-mobius-app.md```

1. It seems we need to use Spark 2.0.2 to run the release version of Mobius, not 1.6.*
2. The WordCount example Batch, it is pointing to the wrong EXE.

**Comment by skaarthik** [comment]
@kmleow thanks for reporting the issues.

1. Branches 'master' and 'branch-2.0' and the latest release need Spark 2.0.*. However there other branches and related that need earlier versions of Spark.
2. Can you provide more details?

**Comment by kmleow** [comment]
@skaarthik 
The WordCount example Batch, the documentation points to ```SparkClrPi.exe``` when it actually should be ```SparkClrWordCount.exe```.

**Comment by skaarthik** [comment]
@kmleow thanks. It will be fixed. Feel free to send a PR with the fix.

**Comment by kmleow** [comment]
@skaarthik [PR 648](https://github.com/Microsoft/Mobius/pull/648) made

**Comment by skaarthik** [comment]
Thanks @kmleow . Merged your changes.
