### ISSUE TITLE
How to use Option "eventhubs.filter.offset" ?

### ISSUE THREAD

**Issue by gepolv** [Microsoft/Mobius#653]
From here:
https://github.com/Microsoft/Mobius/blob/master/csharp/Adapter/Microsoft.Spark.CSharp/Streaming/EventHubsUtils.cs

This parameter:

"eventhubs.filter.offset": Starting offset of EventHubs, default to "-1"

If I want to set the initial offset to current time, what should I do here?

Thanks

**Comment by skaarthik** [comment]
Mobius just passes eventhubs parameters to spark-eventhubs library. You may want to refer to its documentation or raise question in its Github repo.
