### ISSUE TITLE
Loading json from AWS S3 results in  " java.io.IOException: No FileSystem for scheme: s3" error

### ISSUE THREAD

**Issue by janosfk** [Microsoft/Mobius#656]
I'm trying to read an AWS S3 json file (have Spark/Scala version working):

            var spark = SparkUtil.GetSparkSession("LoadFromS3");
            SparkContext sc = SparkUtil.GetSparkContext(spark);

            sc.HadoopConfiguration.Set("fs.s3n.awsAccessKeyId", "valid key");
            sc.HadoopConfiguration.Set("fs.s3n.awsSecretAccessKey", "valid secret key");

            var scans = spark.Read().Json("s3://bucketname/file.json");
------------And the utility functions-----------------

	public static SparkSession GetSparkSession (string appName)
        {
            return SparkSession
                .Builder()
                .AppName(appName)
                .Master("local[*]")
                .GetOrCreate();
        }

        public static SparkContext GetSparkContext(SparkSession spark)
        {
            var contextProp = spark.GetType().GetProperty("SparkContext", BindingFlags.NonPublic | BindingFlags.Instance);
            return contextProp?.GetValue(spark) as SparkContext;
        }

Any suggestion?
Thank you,
János

**Comment by skaarthik** [comment]
You may need to include path to S3 jar in Mobius class path (set in sparkclr-submit.cmd).

**Comment by janosfk** [comment]
That solved the problem. Read from/to S3 works. However when I try to call an action on RDD, I get time error sometime :
java.net.SocketTimeoutException: Accept timed out
        at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at org.apache.spark.api.python.PythonRDD$$anon$2.run(PythonRDD.scala:697)

Is there a place I can change this time out?
Thanks,
János
