### ISSUE TITLE
FSharp API?

### ISSUE THREAD

**Issue by TonyAbell** [Microsoft/Mobius#66]
Would this project be open to supporting an FSharp API wrapper?  

Something to make the it easier to write idiomatic FSharp code.

**Comment by danielli90** [comment]
The current focus for SparkCLR is on C#. We heard interest in writing Spark driver program in F#. We may be able to investigate the design post M2 (https://github.com/Microsoft/SparkCLR/milestones). We do believe the design for C# support can be leveraged for F# support. 

Tag this issue as "Future". Your comments on the impact and the benefit for SparkCLR to support F#, will help us prioritize post M2.

**Comment by jthelin** [comment]
@TonyAbell -- Looks like you have lots of experience using F# so any insight you can provide would be very useful. 

As @danielli90 said, "in theory" SparkCLR should work with any .NET language, but I know there are often subtle things that C# programmers can (unknowingly) do with their APIs that can make it harder (or easier) for F# programmer to use them.

For example, on [another project](https://github.com/dotnet/orleans), we had to create special support for serializing F# lists so they would round-trip correctly back to F#.

If you have any specific guideline or suggestions about how to create "F# friendly APIs" (or even send a PR ;) that would probably help speed things along considerably.

**Comment by skaarthik** [comment]
@TonyAbell - F# support is something that has come several times in our discussions. I am interested in formally collecting data on how F# support would benefit the Spark community and why having C# API is not enough. Please share your comments. We can use this issue to collect data from other interested folks. We will use the data collected to make decisions on priority, scope, dates etc.

**Comment by dsyme** [comment]
@skaarthik @jthelin Please feel free to get in touch with myself and David Stephens at Microsoft about this.

**Comment by isaacabraham** [comment]
@skaarthik there are many cases where a C# API can be consumed by F# but as @TonyAbell rightly points out, it doesn't lead to idiomatic (or limited) F# (and occasionally won't work).

A good example of this is LINQ - whilst it works over F# sequences, lists etc. (which implement IEnumerable<T>), F# comes with its own collection libraries that have support for F# features such as partial function application, tuples, pipelining etc. etc. etc.... that LINQ does not have.

**Comment by dsyme** [comment]
@isaacabraham @skaarthik  I'd be quite happy just to see F# samples properly supporting a Scala --> F# transition. I don't necessarily think this needs a new API. 

Putting aside technical matters, it is very clear that most Scala programmers would consider F# their natural transition language on the .NET platform: F# has a huge amount of appeal to Scala programmers both in design and cultural aspects. So it totally makes sense for Spark CLR to support a Scala --> F# transition as well as a Java --> C# transition.  You expect you simply won't be able to attract Scala programmers to Spark CLR with C# alone.

**Comment by isaacabraham** [comment]
@dsyme agreed - but it's highly likely that some wrapper functions etc. will naturally evolve to matter the experience more natural to the F# person, or perhaps DUs mapping to case classes etc..

**Comment by dsyme** [comment]
@isaacabraham Yes, that's likely.  But I think the priority thing is to have good getting-started material and docs aimed at the F# programmer.  It would help if we just changed the README and docs to make it clear that F# programmers are welcomed and encouraged to use SparkCLR (likewise Scala/Spark programmers wanting to transition to F#/Spark).

**Comment by forki** [comment]
> formally collecting data on how F# support would benefit the Spark community and why having C# API is not enough

You want to play in Scala league, right? All the Scala people I know would not go back to C#.

**Comment by skaarthik** [comment]
> You want to play in Scala league, right? All the Scala people I know would not go back to C#.

I don't believe developers who use Scala for Spark app development would give up Scala and adopt Mobius just because it has F# API.

My personal opinion is that the goal of Mobius is to enable .NET developers build Spark apps without having to invest in Scala or other languages supported in Spark. C# being the most popular language in .NET development (AFAIK) became the pragmatic choice for the .NET API for Spark with the idea that other .NET languages could reuse the C# API for now and that the support for other .NET languages in Mobius would evolve based on the demand.

To make the right decisions on the F# API, following are the earnest questions I have (as someone who is not familiar with F#):
* Who is the Spark dev persona that would like F# API in Mobius and why that dev cannot wrap C# API in F# at the Mobius app-level (as opposed to F# API available in Mobius)?
* What would it take to build F# API? Is it just about wrapping C# implementation as idiomatic F# API or are there special design considerations in adding F# API?

Any specific recommendations or concrete pointers to the questions above would help shape up the proposal for F# API.

*Note* - I do not intend to start the religious debate on C# vs. F#. To keep the discussion constructive, I request all to limit the responses to the additional value of F# API in Mobius and what the minimum-viable-product for the F# API would look like.

**Comment by isaacabraham** [comment]
@skaarthik you're right, no-one wants this to be a religious debate. it's about exposing Mobius to as many developers as possible; this includes existing C# and F# developers as well potentially in the CoreCLR world other language developers on non-Windows OSes that wish to use .NET.

I think a C# wrapper in F# might well be sufficient for many use cases, but perhaps a good starting might be to review the PR for Tuple support and give your feedback?

**Comment by slyons** [comment]
In my off time I started piecing together a custom query expression builder that leverages the existing C# api and just makes it more F# friendly. F# is very popular amongst data science and financial developers and it would be useful to at least have it as an option. The query expression syntax works well with Spark's lazy evaluation.

    let rdd = sparkContext.Parallelize(seq {0 .. 100})
                  |> FSpark.cache

    let otherrdd = FSpark.sparkrdd { 
            let! foo = rdd
            map (fun x -> sprintf "%d" x)
            where (fun x -> x.Length > 0)
            countByValue
     }

**Comment by skaarthik** [comment]
@slyons - sounds great. 

There have been discussions but currently Mobius does not have a REPL experience. Having REPL experience for Mobius using F# would be awesome.

**Comment by skaarthik** [comment]
@isaacabraham - added my comments to your PR for Tuple support

**Comment by skaarthik** [comment]
Details on F# support in Mobius available at https://github.com/Microsoft/Mobius/blob/master/notes/spark-fsharp-mobius.md.

Merged Tuple support in b95520eff8ea63914fd58bb83a932d1015bcce46

Closing this issue. Please reopen or create a new issue if needed.
